Docs(Lambda): Use a better compose file for dgraph + lambda
dgraph-io/dgraph-docs pull request #102
Opened 2021-03-09 03:59 UTC by marcosnils

This copose spec has several advantages over the current example like: 

- It uses the same draph image as all the other examples to start Dgraph alpha + zero 
- I've removed the (version) in the compose spec since that's not required anymore given the latest compose spec updates
- I'm using env variables to set the correct lambda URL instead of using custom arguments .

2021-03-09 03:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=102) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=102) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph-docs?pullRequest=102) it.</sub>

2021-03-31 22:16 UTC, darkn3rd requested changes

2021-03-31 22:16 UTC, darkn3rd commented on content/graphql/lambda/server.md
>          read_only: true
Long form of volumes is not need and is inconsistent to dgraph volumes definition.  Just have:
  volumes:
    - ./gql/script.js:/app/script/script.js:ro

2021-03-31 22:16 UTC, darkn3rd commented on content/graphql/lambda/server.md
> +      - "dgraph"
A new network definition is not need, as Docker Compose by defaults creates a new network for everything defined in the docker-compose.yml

2021-03-31 22:16 UTC, darkn3rd commented on content/graphql/lambda/server.md
>  ```
A new network definition is not needed, as Docker Compose by defaults creates a new network for everything defined in the docker-compose.yml

2021-03-31 22:16 UTC, darkn3rd commented on content/graphql/lambda/server.md
> +      - "dgraph"
A new network definition is not need, as Docker Compose by defaults creates a new network for everything defined in the docker-compose.yml

2021-03-31 22:16 UTC, darkn3rd commented on content/graphql/lambda/server.md
>  ```
This code block is redundant and not needed as it is already in the docker-compose file below.  Also it is invalid syntax for docker-compose spec

2021-03-31 22:16 UTC, darkn3rd commented on content/graphql/lambda/server.md
> +      - "dgraph:/dgraph"
Quotes are not needed.

2021-03-31 22:16 UTC, darkn3rd commented on content/graphql/lambda/server.md
> +  dgraph:
dgraph: hash cannot have a null value; if there are no values, then use an empty hash, i.e. `{}` for the value.

```yaml
volumes:
  dgraph: {}
```

2021-03-31 22:16 UTC, darkn3rd commented on content/graphql/lambda/server.md
>        - 8686:8686
quotes should around ports to be consistent with dgraph service above, or remove quotes from dgraph service ports list items.  Either way.

2021-03-31 22:49 UTC, marcosnils commented on content/graphql/lambda/server.md
> +      - "dgraph:/dgraph"
They are recommended though. Check https://docs.docker.com/compose/compose-file/compose-file-v3/#ports

> When mapping ports in the HOST:CONTAINER format, you may experience erroneous results when using a container port lower than 60, because YAML parses numbers in the format xx:yy as a base-60 value. For this reason, we recommend always explicitly specifying your port mappings as strings.

2021-03-31 22:49 UTC, marcosnils commented on content/graphql/lambda/server.md
> +      - "dgraph"
True, I like having it for the sake of good practices and clarify. I can remove it

2021-03-31 22:49 UTC, marcosnils commented on content/graphql/lambda/server.md
> +  dgraph:
The compose documentation doesn't say anything about this: https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes

2021-03-31 22:49 UTC, marcosnils commented on content/graphql/lambda/server.md
>          read_only: true
This is how it was originally specified. If short form is preferred now, I can change it

2021-04-01 16:22 UTC, darkn3rd commented on content/graphql/lambda/server.md
> +      - "dgraph:/dgraph"
That's fine.

2021-04-01 16:32 UTC, darkn3rd commented on content/graphql/lambda/server.md
> +  dgraph:
As an implementation example, the Docker Compose, team chose to communicate an empty list `{}`. rather than null, which is the current value.

* https://docs.docker.com/compose/wordpress/

Generally, it is good form to communicate a value rather than leave it as implicit null for instructional material, especially for new users.

2021-04-01 16:35 UTC, darkn3rd commented on content/graphql/lambda/server.md
> +    image: dgraph/standalone
May want to communicate the version `latest`.

2021-04-01 16:39 UTC, darkn3rd reviewed
I made some comments and recommended changes at your discretion.  

* the quotes on ports are fine, they are now consistent.
* use explicit values rather than implicit null values
* add explicit tag of `latest`, as users may not know this is the implicit tag if not specified for docker hub, for `dgraph/standalone`.

2021-04-01 16:43 UTC, darkn3rd commented on content/graphql/lambda/server.md
> +      - "dgraph"
It is really only used if you have containers on the same network outside of the docker-compose.  But then if we are adding networking, are we teaching docker-compose or lambda.

2021-04-01 17:02 UTC, darkn3rd approved these changes

2021-04-01 17:31 UTC, bucanero commented
hello @marcosnils, could you sync your PR with our `master` branch? thanks

2021-04-01 23:45 UTC, marcosnils commented on content/graphql/lambda/server.md
> +    image: dgraph/standalone
Iif not specified latest is used.

2021-04-01 23:46 UTC, marcosnils commented
> hello @marcosnils, could you sync your PR with our `master` branch to resolve the conflicts? thanks

Done, hopefully we can get this merged now. It's already taking very long for a very simple change.

2021-04-02 12:10 UTC, bucanero commented on content/graphql/lambda/server.md
> +Here's a complete Docker example that uses the base dgraph image and adds support to lambda server
```suggestion
Here's a complete Docker example that uses the base Dgraph image and adds Lambda server support:
```

2021-04-02 12:12 UTC, bucanero approved these changes

2021-04-02 12:13 UTC, merged