Docs (GraphQL): 21.03 feature documentation for federation
dgraph-io/dgraph-docs pull request #104
Opened 2021-03-09 12:01 UTC by vardhanapoorv

Docs regarding support for Apollo federation.
Fixes DOC-156

2021-03-09 17:34 UTC, aaroncarey commented on content/graphql/federation/index.md
> +weight = 14
Please add a "description" under "title" to give us a description for SEO. Suggestion:

```
description = "Dgraph now supports Apollo federation so that you can create a gateway GraphQL service that includes the Dgraph GraphQL API and other GraphQL services."

2021-03-09 17:56 UTC, aaroncarey reviewed
Great content! I added a few comments.

2021-03-09 17:56 UTC, aaroncarey commented on content/graphql/federation/index.md
> +Starting from release version 21.03 support has been added for Apollo federation. Hence making it possible to use Dgraph GraphQL API with other GraphQL services through a single gateway.
```suggestion
Dgraph supports Apollo federation starting in release version 21.03. This lets you create a gateway GraphQL service that includes the Dgraph GraphQL API and other GraphQL services.
```

2021-03-09 17:56 UTC, aaroncarey commented on content/graphql/federation/index.md
> +Starting from release version 21.03 support has been added for Apollo federation. Hence making it possible to use Dgraph GraphQL API with other GraphQL services through a single gateway.
Edited to remove passive voice

2021-03-09 17:56 UTC, aaroncarey commented on content/graphql/federation/index.md
> +The current implementation supports 3 directives, namely `@key`, `@extends`, and `@external`.
```suggestion
The current implementation supports the following three directives: `@key`, `@extends`, and `@external`.
```

2021-03-09 17:56 UTC, aaroncarey commented on content/graphql/federation/index.md
> +This directive takes one field argument inside it which is called `@key` field. There are few limitations on how to use `@key` directives.
```suggestion
This directive takes one field argument inside it: the `@key` field. There are few limitations on how to use `@key` directives:
```

2021-03-09 17:56 UTC, aaroncarey commented on content/graphql/federation/index.md
> +User can define `@key` directive only once for a type, Support for multiple key types is not provided yet.
The items on lines 19 and 20 should be three bullets, IMO (slight suggested rewording):

* Users can define the `@key` directive only once for a type
* Support for multiple key types is not currently available.
* Since the `@key` field acts as a foreign key to resolve entities from the service where it is extended, the field provided as an argument inside the `@key` directive should be of `ID` type or have the `@id` directive on it.

2021-03-15 11:15 UTC, minhaj-shakeel commented on content/graphql/federation/index.md
> +Remember to add the `Extended Definitions` block from the generated schema of Dgraph GraphQL to the other GraphQL services schemas that are part of the gateway. This needs to be done otherwise the Ap
We don't need to append `Extended Definitions` now. Please remove this block.

2021-03-15 12:09 UTC, vardhanapoorv commented on content/graphql/federation/index.md
> +Remember to add the `Extended Definitions` block from the generated schema of Dgraph GraphQL to the other GraphQL services schemas that are part of the gateway. This needs to be done otherwise the Ap
Done

2021-03-15 13:12 UTC, abhimanyusinghgaur requested changes

2021-03-15 13:12 UTC, abhimanyusinghgaur commented on content/graphql/federation/index.md
> +
About `@requires`, we also need to add that:
```
If you feel the need to use `@requires`, you probably also want to add custom logic on such fields. You can do that using `@lambda`/`@custom(http: {...})`
```
See, this PR for example usage of `@requires` with `@lambda` and accordingly add an example here with `@lambda`: https://github.com/dgraph-io/dgraph/pull/7565

2021-03-15 13:12 UTC, abhimanyusinghgaur commented on content/graphql/federation/index.md
> +Currently we only support federated queries, not federated mutations. We might support it in the future.
The apollo spec itself doesn't support federated mutations. So, I don't think we should even say that we might support them later.

2021-03-15 13:12 UTC, abhimanyusinghgaur commented on content/graphql/federation/index.md
> +## Gateway supported directives
I feel this section is also irrelevant to users. They shouldn't be concerned about the bugs in the underlying libs. They only want to use the feature.
So, let's remove this section too.

2021-03-15 13:12 UTC, abhimanyusinghgaur commented on content/graphql/federation/index.md
> +Use the admin endpoint to query for the generated schema -
Let's remove the `getGQLSchema` thing from here, it is not relevant.

2021-03-16 08:48 UTC, abhimanyusinghgaur approved these changes

2021-03-16 23:05 UTC, aaroncarey commented on content/graphql/federation/index.md
> +- Users can define the @key directive only once for a type
```suggestion
- Users can define the `@key` directive only once for a type
```

2021-03-16 23:06 UTC, aaroncarey commented on content/graphql/federation/index.md
> +- Since the @key field acts as a foreign key to resolve entities from the service where it is extended, the field provided as an argument inside the @key directive should be of ID type or have the @i
```suggestion
- Since the `@key` field acts as a foreign key to resolve entities from the service where it is extended, the field provided as an argument inside the `@key` directive should be of `ID` type or have the `@id` directive on it.
```

2021-03-16 23:09 UTC, aaroncarey commented on content/graphql/federation/index.md
> +This directive is provided to give support for extended definitions. Suppose the above defined `User` type is defined in some other service. Users can extend it in Dgraph's GraphQL service by using t
```suggestion
This directive provides support for extended definitions. For example, if the above-defined `User` type is defined in some other service, you can extend it in Dgraph's GraphQL service by using the `@extends` directive, as follows: 
```

2021-03-16 23:10 UTC, aaroncarey commented on content/graphql/federation/index.md
> +The same is also achievable with the `extend` keyword, i.e., user has the choice to choose between `extend type User ...` or `type User @extends ...`.
```suggestion
You can also achieve this with the `extend` keyword; so you have a choice between two types of syntax to extend a type into your Dgraph GraphQL service: `extend type User ...` or `type User @extends ...`.
```

2021-03-16 23:11 UTC, aaroncarey commented on content/graphql/federation/index.md
> +This directive is used when the given field is not stored in this service. It can only be used on extended type definitions. As it is used above on the `id` field of `User` type.
```suggestion
You use this directive when the given field is not stored in this service. It can only be used on extended type definitions. For example, it is used in the example shown above on the `id` field of the `User` type.
```

2021-03-16 23:13 UTC, aaroncarey commented on content/graphql/federation/index.md
> +This directive is used on a field that tells the gateway to return a specific fieldSet from the base type while fetching the field.
```suggestion
You use this directive on a field that tells the gateway to return a specific `FieldSet` from the base type while fetching the field. 
```

2021-03-16 23:15 UTC, aaroncarey commented on content/graphql/federation/index.md
> +This directive is used on a field that tells the gateway to return a specific fieldSet from the base type while fetching the field.
Per https://www.apollographql.com/docs/federation/federation-spec/#scalar-_fieldset, we should either write "fieldset" or `_FieldSet`. The first one makes more sense to me in this context, but I could be wrong.

2021-03-16 23:17 UTC, aaroncarey commented on content/graphql/federation/index.md
> +While fetching `Review.product` from the `review` service, and if the `name` or `price` is also queried, the gateway will fetch these from the `review` service itself, meaning that it also resolves t
```suggestion
While fetching `Review.product` from the `review` service, and if the `name` or `price` is also queried, the gateway will fetch these from the `review` service itself. So, the `review` service also resolves these fields, even though both fields are `@external`.
```

2021-03-16 23:17 UTC, aaroncarey commented on content/graphql/federation/index.md
> +While fetching `Review.product` from the `review` service, and if the `name` or `price` is also queried, the gateway will fetch these from the `review` service itself, meaning that it also resolves t
Breaking this into two sentences makes it easier to parse (and machine-translate)

2021-03-16 23:19 UTC, aaroncarey commented on content/graphql/federation/index.md
> +This directive is used on a field to annotate the fieldSet of the base type. It is used to develop a query plan where the required fields may not be needed by the client, but the service may need add
```suggestion
You use this directive on a field to annotate the fieldset of the base type. You can use it to develop a query plan where the required fields may not be needed by the client, but the service may need additional information from other services. 
```

2021-03-16 23:21 UTC, aaroncarey commented on content/graphql/federation/index.md
> +Using `@requires` alone on a field doesn't make much sense. In cases, where you feel the need to use `@requires`, you would want some custom logic on that field too. You can achieve that using `@lamb
```suggestion
Using `@requires` alone on a field doesn't make much sense. In cases where you need to use `@requires`, you should also add some custom logic on that field. You can add such logic using the `@lambda` or `@custom(http: {...})` directives.
```

2021-03-16 23:22 UTC, aaroncarey commented on content/graphql/federation/index.md
> +The queries for `Astronaut` are not exposed to the gateway since it will be resolved through the `_entities` resolver. Although these queries will be available on the Dgraph GraphQL API endpoint.
```suggestion
The queries for `Astronaut` are not exposed to the gateway because they are resolved through the `_entities` resolver. However, these queries are available on the Dgraph GraphQL API endpoint.
```

2021-03-16 23:23 UTC, aaroncarey commented on content/graphql/federation/index.md
> +The mutation `addAstronaut` takes `AddAstronautInput` which is generated as -
```suggestion
The mutation `addAstronaut` takes `AddAstronautInput`, which is generated as follows:
```

2021-03-16 23:25 UTC, aaroncarey commented on content/graphql/federation/index.md
> +Even though the `id` field is of `ID` type which should be ideally generated internally by Dgraph. In this case, it should be provided as input since currently federated mutations aren't supported. T
```suggestion
The `id` field is of `ID` type, which is usually generated internally by Dgraph. In this case, it's provided as an input because federated mutations aren't currently supported. The user should provide the same `id` value that is present in the GraphQL service where the type  `Astronaut` is defined.
```

2021-03-16 23:26 UTC, aaroncarey commented on content/graphql/federation/index.md
> +For example, let's take that the type `Astronaut` is defined in some other service `AstronautService` as -
```suggestion
For example, let's assume that the type `Astronaut` is defined in some other service, `AstronautService`, as follows:
```

2021-03-16 23:27 UTC, aaroncarey commented on content/graphql/federation/index.md
> +When adding an object of type `Astronaut`, first it should be added into `AstronautService` service and then the `addAstronaut` mutation should be called with value of `id` provided as an argument wh
```suggestion
When adding an object of type `Astronaut`, you should first add it to the `AstronautService` service. Then, you can call the `addAstronaut` mutation with the value of `id` provided as an argument that must be equal to the value in `AstronautService` service.
```

2021-03-16 23:32 UTC, aaroncarey commented
Approved with suggested edits. You might want to add a "Known Issues" section at the bottom that will make it easy to see the limitation around mutations at-a-glance (especially if there are any other limitations that we want to highlight).

2021-03-16 23:33 UTC, aaroncarey commented on content/graphql/federation/index.md
> +weight = 14
Thanks for adding this!

2021-03-17 08:15 UTC, vardhanapoorv commented
@aaroncarey Abhimanyu mentioned that those things aren't supported by Apollo federation itself and hence it isn't a limitation, we shouldn't be mentioning it.

2021-03-18 15:41 UTC, merged