docs(enterprise): Add Vault to access-control-lists.md
dgraph-io/dgraph-docs pull request #105
Opened 2021-03-09 15:12 UTC by bucanero

Fixes DOC-174

2021-03-09 15:23 UTC, ajeetdsouza requested changes

2021-03-09 15:23 UTC, ajeetdsouza commented on content/enterprise-features/access-control-lists.md
> +3. Vault Server must instantiate a KV store containing a K/V for Dgraph. The `enc-field` option must be the KV-v1 or KV-v2 format. The vaule of this key is the encryption key that Dgraph will use. Th
- The Vault KV Secrets Engine has two versions (Version 1, Version 2). `enc-field` is the name of the key containing the encryption key at the specified path (the two are unrelated).
- Since we support both versions of Vault, it doesn't matter which version the user is on. For that reason, I'm not sure we really need to mention it.
- The encryption key must be 16, 32, or 64 bytes in length.

2021-03-09 15:23 UTC, ajeetdsouza commented on content/enterprise-features/access-control-lists.md
> +4. Vault Server must contain a K/V for the ACL key. The `acl-field` option must be the KV-v1 or KV-v2 format. The vaule of this key is the ACL secret key that Dgraph will use. This key must be 16,24
- Same as above.
- The ACL key can be any length >= 32 bytes.

2021-03-09 23:01 UTC, bucanero commented on content/enterprise-features/access-control-lists.md
> +4. Vault Server must contain a K/V for the ACL key. The `acl-field` option must be the KV-v1 or KV-v2 format. The vaule of this key is the ACL secret key that Dgraph will use. This key must be 16,24
fixed

2021-03-09 23:02 UTC, bucanero commented on content/enterprise-features/access-control-lists.md
> +3. Vault Server must instantiate a KV store containing a K/V for Dgraph. The `enc-field` option must be the KV-v1 or KV-v2 format. The vaule of this key is the encryption key that Dgraph will use. Th
fixed

2021-03-10 10:07 UTC, ajeetdsouza commented on content/enterprise-features/access-control-lists.md
> +4. Vault Server must contain a K/V for the ACL key. This key will be needed for the `acl-field` option, to set the ACL secret key that Dgraph will use. This key must have at least 256-bits (32 ASCII
Small correction: we don't actually need both of these subflags. If `--vault` is being used, then at least one of `enc-field` and `acl-field` must be set. If `enc-field` is set, then encryption is enabled; if `acl-field` is set, then ACL is enabled. If neither of them are set, then it makes no sense to be using the vault flag, so this will throw an error.

For that reason, if `enc-field` is set, we can't also be using `--encryption_key_file`, and if `acl-field` is set, we can't also be using `--acl="secret-file=..."`

2021-03-10 12:40 UTC, bucanero commented on content/enterprise-features/access-control-lists.md
> +4. Vault Server must contain a K/V for the ACL key. This key will be needed for the `acl-field` option, to set the ACL secret key that Dgraph will use. This key must have at least 256-bits (32 ASCII
fixed: I removed references to `enc-field`, as this article refers only to ACL. The vault encryption settings remain in the Encryption articles.

2021-03-10 12:43 UTC, merged