Docs (GraphQL): 21.03 feature documentation for multiple @id fields in a type
dgraph-io/dgraph-docs pull request #110
Opened 2021-03-10 18:42 UTC by selectiveduplicate

Documentation for using multiple `@id` fields in a type as per PR: https://github.com/dgraph-io/dgraph/pull/7235.
Addresses [DOC-170](https://dgraph.atlassian.net/browse/DOC-170).

2021-03-10 19:21 UTC, JatinDevDG requested changes

2021-03-10 19:21 UTC, JatinDevDG commented on content/graphql/schema/ids.md
> +
Can you please change it to something like this:
`You can then use multiple `@id` fields in arguments to get queries, and  while searching these fields will be combined with "And" connective. For example, for the above schema, you can send a `getBook` query like the following:`

2021-03-10 19:21 UTC, JatinDevDG commented on content/graphql/schema/ids.md
> +{{% /notice %}}
Please change this to something like this

`If in a type, there are multiple @id fields, then in arguments to get Query these fields will be optional, and if in a type there is only one field defined with either `@id` or `ID`, then that will be a required field in the arguments of get Query.`

2021-03-10 19:45 UTC, verneleem commented on content/graphql/schema/ids.md
> +As with `ID` types, Dgraph generates queries and mutations so you can query, update and delete data in nodes, using the fields with the `@id` directive as references.
This fixes the wording in question here. Thank you!

2021-03-10 19:45 UTC, verneleem commented on content/graphql/schema/ids.md
>  In a single-page app, you could render the page for `http://.../user/Erik` when a user clicks to view the author bio page for that user. Your app can then use a `getUser(username: "Erik") { ... }` Gr
Should this be moved above line 58? It feels like we are switching to a new schema for Books and then going back to the User schema. I think it would flow better if this was closer to the User schema.

2021-03-11 05:27 UTC, JatinDevDG commented on content/graphql/schema/ids.md
>  In a single-page app, you could render the page for `http://.../user/Erik` when a user clicks to view the author bio page for that user. Your app can then use a `getUser(username: "Erik") { ... }` Gr
yeah, we should move this to above line 58.

2021-03-11 10:37 UTC, JatinDevDG approved these changes

2021-03-11 13:12 UTC, bucanero commented on content/graphql/schema/ids.md
> +As with `ID` types, Dgraph generates queries and mutations so you can query, update and delete data in nodes, using the fields with the `@id` directive as references.
```suggestion
As with `ID` types, Dgraph generates queries and mutations so you can query, update, and delete data in nodes, using the fields with the `@id` directive as references.
```

2021-03-11 13:14 UTC, bucanero commented on content/graphql/schema/ids.md
> +You can then use multiple `@id` fields in arguments to `get` queries, and while searching, these fields will be combined with the `AND` connective, resulting in a Boolean `AND` operation. For example
```suggestion
You can then use multiple `@id` fields in arguments to `get` queries, and while searching, these fields will be combined with the `AND` operator, resulting in a Boolean `AND` operation. For example, for the above schema, you can send a `getBook` query like the following:
```

2021-03-11 13:21 UTC, bucanero commented on content/graphql/schema/ids.md
> +If in a type, there are multiple `@id` fields, then in arguments to a `get` query these fields will be optional, and if in a type there's only one field defined with either `@id` or `ID`, then that w
```suggestion
If in a type there are multiple `@id` fields, then in a `get` query these arguments will be optional. If in a type there's only one field defined with either `@id` or `ID`, then that will be a required field in the `get` query's arguments.
```

2021-03-11 13:22 UTC, bucanero approved these changes
lgtm, thanks @selectiveduplicate 👍

2021-03-11 13:24 UTC, merged