Docs (GraphQL Subscriptions): Rewording for style, plus gzip compression support
dgraph-io/dgraph-docs pull request #118
Opened 2021-03-12 16:32 UTC by aaroncarey

Per DOC-189

2021-03-12 16:44 UTC, aaroncarey commented on content/graphql/subscriptions/index.md
> +{{% notice "note" %}}
This note is per DOC-189

2021-03-15 05:19 UTC, minhaj-shakeel requested changes

2021-03-15 05:19 UTC, minhaj-shakeel commented on content/graphql/subscriptions/index.md
> +Dgraph uses gzip compression if the GraphQL client's `Sec-Websocket-Extensions`
replace gzip with `permessage-deflate` compression.

2021-03-15 05:19 UTC, minhaj-shakeel commented on content/graphql/subscriptions/index.md
> +Starting in release v21.03, Dgraph supports gzip compression for subscriptions.
Dgraph supports compression for .....

2021-03-15 21:47 UTC, aaroncarey commented on content/graphql/subscriptions/index.md
> +Dgraph uses gzip compression if the GraphQL client's `Sec-Websocket-Extensions`
Done.

2021-03-15 21:47 UTC, aaroncarey commented on content/graphql/subscriptions/index.md
> +Starting in release v21.03, Dgraph supports gzip compression for subscriptions.
Done.

2021-03-17 16:04 UTC, aaroncarey commented
Feedback incorporated, merging

2021-03-17 16:04 UTC, merged