docs (EE): Add FAQ to multitenancy article
dgraph-io/dgraph-docs pull request #135
Opened 2021-03-22 14:26 UTC by bucanero

fixes DOC-206

2021-03-22 17:03 UTC, anand-chandrashekar requested changes

2021-03-22 19:41 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +- What is the granularity of the access controls? Is it per graph? Per tenant only?
fixed

2021-03-22 19:41 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +    Previously, Dgraph had ACL across a single instance. With multi-tenancy, Dgraph's ACL controlling scope is by tenant.
fixed

2021-03-22 19:44 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +    while user `Jane Doe`, who belongs to the group `Data Managers`, can be given access to modify predicates.
fixed (using `data editors`)

2021-03-22 19:45 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +- Are tenants a physical separation or a logical one? Does the data needs to be writen twice (e.g., for 2 tenants), or only once?
removed

2021-03-23 04:00 UTC, anand-chandrashekar approved these changes

2021-03-23 12:36 UTC, merged