docs(clients): Add Cloud client example for js-http
dgraph-io/dgraph-docs pull request #156
Opened 2021-04-01 15:12 UTC by bucanero

Fixes DOC-80

2021-04-06 13:20 UTC, OmarAyo commented on content/clients/javascript/http.md
> +If you want to connect to Dgraph running on your [Dgraph Cloud](https://slash.dgraph.io) instance, then all you need is the URL of your Dgraph Cloud endpoint and the API key. You can get a client usi
the link for Dgraph Cloud is wrong, replace it with cloud.dgraph.io instead

2021-04-06 13:21 UTC, OmarAyo commented on content/clients/javascript/http.md
> +//here we pass the slash endpoint
replace the `slash endpoint` with `cloud endpoint`

2021-04-06 13:23 UTC, bucanero commented on content/clients/javascript/http.md
> +If you want to connect to Dgraph running on your [Dgraph Cloud](https://slash.dgraph.io) instance, then all you need is the URL of your Dgraph Cloud endpoint and the API key. You can get a client usi
```suggestion
If you want to connect to Dgraph running on your [Dgraph Cloud](https://cloud.dgraph.io) instance, then all you need is the URL of your Dgraph Cloud endpoint and the API key. You can get a client using them as follows:
```

2021-04-06 13:24 UTC, bucanero commented on content/clients/javascript/http.md
> +//here we pass the slash endpoint
```suggestion
//here we pass the cloud endpoint
```

2021-04-06 13:24 UTC, bucanero commented on content/clients/javascript/http.md
> +If you want to connect to Dgraph running on your [Dgraph Cloud](https://slash.dgraph.io) instance, then all you need is the URL of your Dgraph Cloud endpoint and the API key. You can get a client usi
fixed

2021-04-06 13:24 UTC, bucanero commented on content/clients/javascript/http.md
> +//here we pass the slash endpoint
fixed

2021-04-06 13:28 UTC, OmarAyo commented on content/clients/javascript/http.md
> +    "https://super-pail.us-west-2.aws.cloud.dgraph.io",
you may want to clarify that they need to remove the `/graphql' endpoint if they copy directelly their endpoint from the dashboar. 

As when copying it from the dashboard the endpoint will be: `https://super-pail.us-west-2.aws.cloud.dgraph.io/graphql` but here the need to remove `/graphql` at the end - if this is not done they will get the following error from node:
```
(node:31883) UnhandledPromiseRejectionWarning: HTTPError: Invalid status code = 404
```

2021-04-06 14:25 UTC, OmarAyo requested changes
please address changes

2021-04-08 13:14 UTC, bucanero commented on content/clients/javascript/http.md
> +    "https://super-pail.us-west-2.aws.cloud.dgraph.io",
fixed

2021-04-08 13:15 UTC, merged