Multi-tenancy fixes
dgraph-io/dgraph-docs pull request #179
Opened 2021-04-14 10:02 UTC by OmarAyo

this PR fixes some wrong statements/commands in our current multi-tenancy doc

2021-04-14 10:18 UTC, NamanJain8 requested changes

2021-04-14 10:18 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +The super admin is used only for database admininstration operations, such as exporting data of all tenants. Guardian of the galaxy cannot read across tenats.
typo `tenants`

2021-04-14 10:18 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> -  - They can add users to groups inside the namespace
Why are we removing this? Guardian of a namespace can create users within their namespace.

2021-04-15 01:18 UTC, OmarAyo commented on content/enterprise-features/multitenancy.md
> -  - They can add users to groups inside the namespace
@NamanJain8 AFAIK they can only create a namespace that will also create the guardian of namespace group that has the groot user. IDK if the guardian of galaxy users can create other groups or users in other namespaces

2021-04-15 01:29 UTC, OmarAyo commented on content/enterprise-features/multitenancy.md
> +The super admin is used only for database admininstration operations, such as exporting data of all tenants. Guardian of the galaxy cannot read across tenats.
fixed

2021-04-15 20:49 UTC, ahsanbarkati commented on content/enterprise-features/multitenancy.md
> -  - They can add users to groups inside the namespace
That's right. They cannot create users for other namespaces but within the galaxy namespace, they can do anything that a guardian group can do. It includes creating users.

2021-04-15 22:14 UTC, OmarAyo commented on content/enterprise-features/multitenancy.md
> -  - They can add users to groups inside the namespace
ok then let me rephrase it better to clarify that they can only create users/groups within their namespace

2021-04-15 22:29 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +The super admin is used only for database admininstration operations, such as exporting data of all tenants. Guardian of the galaxy users cannot read across tenants.
```suggestion
The super admin is used only for database administration operations, such as exporting data of all tenants. _Guardian of the Galaxy_ members cannot read across tenants.
```

2021-04-15 22:30 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +  - They can create/add users/groups inside their own namespace
```suggestion
  - They can create users and groups inside their own namespace
```

2021-04-15 22:30 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +  - They can query/mutate in their namespace
```suggestion
  - They can query and mutate in their namespace
```

2021-04-15 22:33 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +When using the _Guardian of the Namespace_, then no need to specify the namespace in the GraphQL mutation, as they can only export within their own namespace:
```suggestion
When using the _Guardian of the Namespace_, there's no need to specify the namespace in the GraphQL mutation, as they can only export within their own namespace:
```

2021-04-15 22:34 UTC, bucanero commented on content/deploy/fast-data-loading/live-loader.md
> +For example, to preserve the namespace while loading data first you need to create the namespace/s and then run the live loader command:
```suggestion
For example, to preserve the namespace while loading data first you need to create the namespace(s) and then run the live loader command:
```

2021-04-16 11:40 UTC, NamanJain8 approved these changes
Looks good. Thanks @OmarAyo !! 🎉

2021-04-16 11:53 UTC, ahsanbarkati approved these changes
Awesome. Thanks Omar

2021-04-16 12:24 UTC, bucanero approved these changes

2021-04-16 14:25 UTC, merged