Docs (GraphQL) fix nested filter syntax error
dgraph-io/dgraph-docs pull request #232
Opened 2021-06-02 14:52 UTC by verneleem

fix syntax error, normalize indention, and add notice about combining nested filters

2021-06-02 18:52 UTC, bucanero commented on content/graphql/queries/and-or-not.md
> +Nested logic with the same `and`/`or` conjunction can be simplified into a single list.
```suggestion
### Nesting

Nested logic with the same `and`/`or` conjunction can be simplified into a single list.

For example:

```

2021-06-02 18:53 UTC, bucanero commented on content/graphql/queries/and-or-not.md
> +{{% /notice %}}
```suggestion

```

2021-06-02 18:54 UTC, bucanero requested changes
I think we can add a heading instead of a notice box.

2021-06-03 16:59 UTC, aaroncarey approved these changes

2021-06-03 17:06 UTC, bucanero approved these changes

2021-06-03 17:31 UTC, merged