Docs (Dgraph) Improve Dgraph Overview
dgraph-io/dgraph-docs pull request #246
Opened 2021-06-21 17:49 UTC by verneleem

These improvements are based off from user feedback and requests for more context to be added to the docs for new users, mainly related to https://discuss.dgraph.io/t/new-to-dgraph-dql-vs-graphql-endpoints-headers-and-schema-translation/10443

Linked "DQL vs GraphQL" blog article for a reference to not duplicate all of that information again.

Fixes DOC-268
Fixes DOC-333

2021-06-21 17:50 UTC, verneleem commented
FYI @aaroncarey agreed to do a review pass on this PR on 6/24 pro-bono.

2021-06-21 17:55 UTC, danielmai requested changes
I did an initial pass for these suggested edits.

2021-06-21 17:55 UTC, danielmai commented on content/dgraph-overview.md
> +- [Ristrettor](https://dgraph.io/ristretto) - Dgraph's custom built cache
```suggestion
- [Ristretto](https://dgraph.io/ristretto) - Dgraph's custom built cache
```

2021-06-21 17:55 UTC, danielmai commented on content/dgraph-overview.md
> +- Dgraph ([Repo Link](https://github.com/dgraph-io/dgraph)) - the methods and algorithms used to parse DQL (and now GraphQL) and act accordingly
```suggestion
- [Dgraph](https://github.com/dgraph-io/dgraph) - the methods and algorithms used to parse DQL (and now GraphQL) and act accordingly
```

2021-06-21 17:55 UTC, danielmai commented on content/dgraph-overview.md
> +In the beginning there was only a single schema, know known as a DQL Schema. As Dgraph developed,
```suggestion
In the beginning there was only a single schema, known as a DQL Schema. As Dgraph developed,
```

2021-06-21 17:55 UTC, danielmai commented on content/dgraph-overview.md
> +The Dgraph team formed their own language based off from the foundation of GraphQL and initially
```suggestion
The Dgraph team formed their own language based off the foundation of GraphQL and initially
```

2021-06-21 17:55 UTC, danielmai commented on content/dgraph-overview.md
> +inner workings of Dgraph you will find it concists of 3 separate entities:
```suggestion
inner workings of Dgraph you will find it concists of 3 separate entities:
```
```suggestion
inner workings of Dgraph you will find it consists of 3 separate entities:
```

2021-06-24 22:17 UTC, aaroncarey reviewed
Thanks for the chance to review this! Please see https://github.com/dgraph-io/dgraph-docs/pull/248, which has my proposed changes.

2021-06-24 23:44 UTC, danielmai commented
#248 has been merged into this PR :+1: Thanks again, @aaroncarey

2021-06-25 22:11 UTC, aaroncarey commented
> #248 has been merged into this PR 👍 Thanks again, @aaroncarey

My pleasure! I'm happy to pitch in as time allows :)

2021-07-19 17:22 UTC, danielmai approved these changes

2021-07-19 17:30 UTC, merged