Update multitenancy.md
dgraph-io/dgraph-docs pull request #263
Opened 2021-09-09 13:42 UTC by Rajakavitha1

- updated the documentation based on https://github.com/dgraph-io/dgraph/pull/7789

2021-09-09 13:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=263) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph-docs?pullRequest=263) it.</sub>

2021-09-23 07:48 UTC, NamanJain8 requested changes

2021-09-23 07:48 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +The `drop all` and `drop data` operations can be triggered by a [Guardian of the Galaxy](#guardians-of-the-galaxy).
Drop data operation is now namespace-aware. So the guardian of a namespace can trigger drop data for their namespace.

2021-09-23 07:48 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +`drop all` and `drop data` operations are executed at cluster level and deletes across namespaces. Guardian of the namespace can trigger `drop data` operation within the namespace. The `drop data` op
Same here. Drop data is now namespace-aware. Here is the relevant PR https://github.com/dgraph-io/dgraph/pull/7795

2021-09-23 07:48 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +```
The examples are already [here](https://dgraph.io/docs/clients/raw-http/#alter-the-database). Do you think that adding a link should be sufficient here?

2021-09-23 09:13 UTC, Rajakavitha1 commented on content/enterprise-features/multitenancy.md
> +The `drop all` and `drop data` operations can be triggered by a [Guardian of the Galaxy](#guardians-of-the-galaxy).
This was only a word edit for Gaurdian of galaxy.

2021-09-23 09:46 UTC, NamanJain8 approved these changes
This looks good. Just make sure that the relative link works. 🎉

2021-09-23 09:46 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +All other `drop` operations run at namespace level and are namespace specific. For information about other delete options, see [Alter the database]({{< relref "raw-http.md#alter-the-database" >}}).
```suggestion
All other `drop` operations run at namespace level and are namespace specific. For information about other drop options, see [Alter the database]({{< relref "raw-http.md#alter-the-database" >}}). 
```

2021-09-30 15:44 UTC, danielmai approved these changes
I've added some minor changes. Otherwise, this looks good to me!

2021-09-30 15:44 UTC, danielmai commented on content/enterprise-features/multitenancy.md
> +  -H 'X-Dgraph-AccessToken: <your-access -token>' \
```suggestion
  -H 'X-Dgraph-AccessToken: <your-access-token>' \
```

2021-09-30 15:44 UTC, danielmai commented on content/enterprise-features/multitenancy.md
> +`drop all` operation is executed at cluster level and deletes data, and schema across namespaces. Guardian of the namespace can trigger `drop data` operation within the namespace. The `drop data` ope
```suggestion
`drop all` operation is executed at cluster level and deletes data and schema across namespaces. Guardian of the namespace can trigger the `drop data` operation within the namespace. The `drop data` operation deletes all the data but retains the schema. 
```

2021-10-01 05:24 UTC, Rajakavitha1 commented on content/enterprise-features/multitenancy.md
> +`drop all` operation is executed at cluster level and deletes data, and schema across namespaces. Guardian of the namespace can trigger `drop data` operation within the namespace. The `drop data` ope
Hi @danielmai I have followed the general and Dgraph Style guide for the usage of comma. "Use commas to separate items in series, and use commas to separate certain kinds of clauses. In a series of three or more items, use a comma before the final and or or."https://discuss.dgraph.io/t/dgraph-developer-documentation-style-guide/10955

2021-10-01 05:39 UTC, danielmai commented on content/enterprise-features/multitenancy.md
> +`drop all` operation is executed at cluster level and deletes data, and schema across namespaces. Guardian of the namespace can trigger `drop data` operation within the namespace. The `drop data` ope
I didn't think this was a list of three items. The comma here looks like it splits the two item list "data and schema".

2021-10-01 07:29 UTC, Rajakavitha1 commented on content/enterprise-features/multitenancy.md
> +`drop all` operation is executed at cluster level and deletes data, and schema across namespaces. Guardian of the namespace can trigger `drop data` operation within the namespace. The `drop data` ope
Thanks @danielmai !!!

2021-10-01 08:05 UTC, merged