Docs(ACL and Multi-Tenancy): Modify pages to include info about managing access for all predicates
dgraph-io/dgraph-docs pull request #264
Opened 2021-09-22 12:24 UTC by rarvikar

Modified pages for Access Control Lists and Multi-Tenancy outlining the process to define access rules over all predicates that exist in a particular namespace. 
The changes pertain to the new feature introduced as per [this Dgraph PR](https://github.com/dgraph-io/dgraph/pull/7991)

2021-09-22 12:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=264) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=264) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph-docs?pullRequest=264) it.</sub>

2021-09-22 14:59 UTC, OmarAyo commented on content/enterprise-features/access-control-lists.md
> +Also, assigning permissions to new predicates as they get created could turn out to be a tedious process for a backend with multi-tenancy enabled.
This feature is unrelated to Multi-tenancy, it's related to ACL. With this feature, we are allowing a group to have RO/W/RW permission over all the predicates in the database (existing and new)

When this comes to the multi-tenancy scenario then in this case the group will be given permission RO/W/RW over all the predicates of a given namespace.

Please re-phase

2021-09-22 16:03 UTC, rarvikar commented on content/enterprise-features/access-control-lists.md
> +Also, assigning permissions to new predicates as they get created could turn out to be a tedious process for a backend with multi-tenancy enabled.
Removed the info pertaining to multi-tenancy and also the subtitle since this can be included under the existing subtitle - "Assign predicate permissions to a group"

2021-09-23 07:39 UTC, OmarAyo commented on content/enterprise-features/access-control-lists.md
> +      set: { rules: [{ predicate: "dgraph.all", permission: 6 }] }
please describe other types numbers of permissions like the one for read only(4), write only (2)

2021-09-23 07:39 UTC, OmarAyo commented on content/enterprise-features/access-control-lists.md
> +
please post the output of that gql mutation

2021-09-23 07:41 UTC, OmarAyo requested changes
please resolve comments

2021-09-23 11:18 UTC, rarvikar commented on content/enterprise-features/access-control-lists.md
> +
Resolving as per discussion

2021-09-23 11:18 UTC, rarvikar commented on content/enterprise-features/access-control-lists.md
> +      set: { rules: [{ predicate: "dgraph.all", permission: 6 }] }
Resolving as per discussions

2021-09-27 11:16 UTC, OmarAyo approved these changes
LGTM

2021-09-27 15:02 UTC, danielmai approved these changes

2021-09-27 15:06 UTC, rarvikar commented
Merging both commits to the base branch.

2021-09-27 15:10 UTC, merged