docs(release): Dgraph v22.0.0 release
dgraph-io/dgraph-docs pull request #336
Opened 2022-10-22 20:12 UTC by MichelDiz

- Update the Releases page with the latest release, Dgraph v22.0.0
- Update the previous versions' patch release information.
- Remove support for  v21.12.x,  v21.03.x, v20.07 and v20.11.
- Set v21.12.x as discontinued

2022-10-24 16:11 UTC, joshua-goldstein approved these changes
👍

2022-10-24 17:49 UTC, skrdgraph commented on content/releases/index.md
> + v21.12.x              | [v21.12.0][]    | No         | December 2021      | December 2022 (discontinued)
can u add discontinued next to v21.12.x - this makes it more specific

2022-10-31 17:55 UTC, meghalims requested changes
Please  keep 21.03.x as Supported and EOL 06/23 In the release matrix. Other changes looks good to me

2022-10-31 17:59 UTC, meghalims approved these changes

2022-10-31 18:01 UTC, merged