Docs(Glossary): glossary revamp
dgraph-io/dgraph-docs pull request #341
Opened 2022-11-23 02:35 UTC by rderbier

Separate glossary, update entries, add to left menu.

2022-11-23 05:07 UTC, Rajakavitha1 requested changes

2022-11-23 05:07 UTC, Rajakavitha1 commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
Can we give a link to https://dgraph.io/docs/tutorial-2/ ?

2022-11-23 05:07 UTC, Rajakavitha1 commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
Can we give a link to : https://dgraph.io/docs/tutorial-2/ for the mental picture.

2022-11-23 05:07 UTC, Rajakavitha1 commented on content/dgraph-glossary.md
> +Dgraph terminology favors the term [Entity](#entity), but the two terms are used interchangeably in our documentation.
We must just stick to Entity in our documentation to avoid confusion . That would also mean we remove all references to node in the documentation.

2022-11-23 05:07 UTC, Rajakavitha1 commented on content/dgraph-glossary.md
> +Dgraph consists of different servers, zero and alpha. Zero servers control the Dgraph database cluster : assign Alpha servers to groups, re-balance data between groups, handle transaction timestamp a
```suggestion
Dgraph consists of zero and alpha. servers. Zero servers control the Dgraph database cluster. It assigns Alpha servers to groups, re-balances data between groups, handles transaction timestamp and UID assignment.
```

2022-11-23 16:52 UTC, rderbier commented on content/dgraph-glossary.md
> +your preferred graph database ! Dgraph is a horizontally scalable and distributed database.
I think we can remove this entry. Dgraph will be explained in the overview. Does not need to be in the glossary IMO.

2022-11-23 16:56 UTC, rderbier commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
Let's talk about links. Glossary is not the menu. I think if the menu is clear people will easily find the concept page about entity and the tutorial about creating entities, edges etc ...
Plus menu is generated automatically where links must be maintained manually.

2022-11-23 16:57 UTC, rderbier commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
what about including a picture here if it helps ?

2022-11-23 16:59 UTC, rderbier commented on content/dgraph-glossary.md
> +Dgraph terminology favors the term [Entity](#entity), but the two terms are used interchangeably in our documentation.
yes. I think we should use entity. But node term is used by graph folks too. So we should keep it in the glossary at least. 
I suggest to keep "but the two terms are used interchangeably in our documentation." until we are have cleaned the references (that could take a while) and then remove it when we have a reasonably low usage of "node"  term in the doc.

2022-11-23 23:55 UTC, Rajakavitha1 commented on content/dgraph-glossary.md
> +your preferred graph database ! Dgraph is a horizontally scalable and distributed database.
Yes!!! lets remove Dgraph as a Glossary entry.

2022-11-23 23:57 UTC, Rajakavitha1 commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
Yes!!! we should be able to dine the term independently. However, if some terms need additional context we can sparingly give a link. Here's of example of the Glossary https://kubernetes.io/docs/reference/glossary/?fundamental=true

2022-11-23 23:59 UTC, Rajakavitha1 commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
Lets avoid the detailed description. Lets try and emulate the Glossary terms similar to https://kubernetes.io/docs/reference/glossary/?fundamental=true

2022-11-24 00:00 UTC, Rajakavitha1 commented on content/dgraph-glossary.md
> +Dgraph terminology favors the term [Entity](#entity), but the two terms are used interchangeably in our documentation.
agreed!! PR to remove node in progress....

2022-11-29 18:03 UTC, rderbier commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
Let's start with 'naked' glossary and then we will add a link to the concept page as we will create one to explain DQL including how to handle  entities and predicates ...

2022-11-30 03:20 UTC, Rajakavitha1 approved these changes

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +Dgraph consists of Zero and Alpha servers. Alpha servers host predicates and indexes. A Dgraph instance or a Dgraph cluster, has at least one Alpha server and can be scaled horizontally by adding mor
This isn't right. Alpha word can mean an Alpha instance, or the Alpha Group. Which are groups of Alphas instances. Zero should be removed from here. Cuz Zero belongs the 0 group. And we don't use the word "Server". Serve is the terminology for a machine who serves something. As Dgraph is a cluster, it is not a server. It is a program that lives between servers.

For example, a database server is a computer who have a database. But it can be any DB. The DB architecture isn't a server per se.

When you say "let's reboot the database server" you are not saying to reboot the database program. But the whole computer. Right?

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +**DQL** Dgraph Query Language is Dgraph's proprietary language to insert, update, delete and query data.
Can we fit "upsert" here somehow?

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
I mentioned before to use arrows instead of lines. Makes more sense and make the user used to directions.

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +**GraphQL** is a declarative language for querying data used by application developers to get the data they need using GraphQL APIs. Dgraph supports the deployment of GraphQL data model (GraphQL sche
Elaborate with: We autogenerate GraphQL Resolvers. In another words, we save your time of doing a ton of code. Less code to maintain.

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
arrows here too

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +Dgraph terminology favors the term [Entity](#entity), but the two terms are used interchangeably in our documentation.
Well, node word is like 99% of the graph market. Entity was a new thing tho. Introduced 2 years ago in the docs.

If we gonna decide which one will be our main terminology. We should check what is the more prominent one.

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +Node is also used in software architecture to reference a physical computer or a virtual machine running a module of Dgraph in a cluster. E.g : 'our archictecture has 3 Alpha nodes'.
Of means "a module of Dgraph in a cluster"?

Node can be a reference for "instance". e.g "3 Alpha instances".

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +- when we store that Alice knows Bob, we may use a predicate ``knows`` for the entity representing Alice. The value of this predicate would be the [uid](#uid) of the entity representing Bob. In that
"entity predicate" feels odd. Cuz the values are also from the entity. Maybe "link predicate"?

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +In Dgraph terminology edges are `entity predicates` i.e an information about the relation between two entities.
We also have "Value Edge" and "Edge". Edges are both value or conections. In general people say "edge" for everything. But when we wanna express the value. We should say "value edge".

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +- when we store that Alice knows Bob, we may use a predicate ``knows`` for the entity representing Alice. The value of this predicate would be the [uid](#uid) of the entity representing Bob. In that
BTW. There are "levels" of usage of the terminology. Like predicates we talk more when talking about DQL schema, in the paper or the core code. But when we are doing Graph models. We never use "predicate". No one uses.

So for me there is a techincal level for paper and code of terms.
A graph model abstraction level.
A general Graph terminology coming from academics(scientific and mathematics).

For example, there's no "predicate" in graph theory as far as I know.

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +**RDF**  RDF 1.1 is a Semantic Web Standards for data interchange. It allows us to make statements about resources. The format of these statements is simple and in the form of `<subject>> <predicate>
RT. We could say as our own RDF. I was using something like "RDF-D". Cuz the format we use is a bit custom. Not used anywhere. Besides we can support some NQuads formats without especial characters.

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +**Sharding** Sharding is a database architecture pattern to achieve horizontal scaling allowing near-limitless scalability. This allows for data to be split and stored in multiple data nodes or serve
'predicate sharding' this is confusing. We don't shard predicates. Predicates tablets that are sharded between groups. We should not make this confusion cuz there are feature requests for predicate sharding.

2022-12-01 21:48 UTC, MichelDiz commented on content/dgraph-glossary.md
> +Dgraph consists of zero and alpha. servers. Zero servers control the Dgraph database cluster. It assigns Alpha servers to groups, re-balances data between groups, handles transaction timestamp and UI
No, Zero is a group or an instance of the group 0. The rest looks okay.

2022-12-01 21:51 UTC, MichelDiz commented on content/dgraph-glossary.md
> +Node is also used in software architecture to reference a physical computer or a virtual machine running a module of Dgraph in a cluster. E.g : 'our archictecture has 3 Alpha nodes'.
what means***

2022-12-05 22:35 UTC, rderbier commented on content/dgraph-glossary.md
> +**DQL** Dgraph Query Language is Dgraph's proprietary language to insert, update, delete and query data.
There is an entry of upsert

2022-12-05 22:35 UTC, rderbier commented on content/dgraph-glossary.md
> +- when we store that Alice knows Bob, we may use a predicate ``knows`` for the entity representing Alice. The value of this predicate would be the [uid](#uid) of the entity representing Bob. In that
Please review latest version where we use node and relationships.

2022-12-09 18:11 UTC, rderbier commented on content/dgraph-glossary.md
> +In the mental picture of a graph: bubbles connected by lines ; the bubbles are nodes, the lines are edges.
Let's deply a first version and I start a new PR for improvements

2022-12-09 18:12 UTC, merged