[Docs revamp] consolidated all export related tasks in one section of howtos
dgraph-io/dgraph-docs pull request #355
Opened 2022-12-09 06:55 UTC by Rajakavitha1

Description: Please include the following in your PR description:
1. A brief, clear description of the change.
2. Link to any related PRs or discuss.dgraph.io posts.
3. If this PR corresponds to a JIRA issue, include "Fixes DOC-###" in the PR description.
3. If this is a breaking change, please put "[Breaking]" in the title. In the description, please put a note with exactly who these changes are breaking for.
4. If you are creating a PR in `main` and you know it needs to be cherry-picked to a release branch, please mention that in your PR description (for example: "cherry-pick to v20.07"). Cherry-pick PRs should reference the original PR.

Note: Create and edit docs in the `main` branch when you can, so that we only cherry-pick out of `main`, not into `main`.
-->

2022-12-13 16:49 UTC, rderbier requested changes
Lot's of work here !

Need some reviews on the export for Dgraph (on prem) as this part is not clear enough for me.

2022-12-13 16:49 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +## Export data on all nodes
```suggestion
## Export data using  the GraphQL admin  endpoint
```

2022-12-13 16:49 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +You can export all nodes by executing a GraphQL mutation on the `/admin` endpoint of an Alpha node ( `localhost:8080/admin`) using any GraphQL client.
```suggestion
You can export the entire data by executing a GraphQL mutation on the `/admin` endpoint of any Alpha node.
```

2022-12-13 16:49 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +*  Specify a list or range of IP addresses allowed to initiate admin operations such as export using the command `dgraph alpha --security whitelist <IP address>`.
I would remove this line. It's about securing DB access and is explained elsewhere.

2022-12-13 16:49 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +This mutation triggers an export for all Alpha groups of the cluster.
```suggestion
This mutation triggers the export.
```

2022-12-13 16:49 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +The export data of the group:
we should better explain what's going on.
Maybe 
This mutation triggers the export : the Alpha node leader of each Alpha group will write an export file for the group in the directory that was specified by the --export parameter used when launching the node.
Depending on you Dgraph configuration you may obtain several files (one per Alpha group).

We recommend that you copy the files from the alpha server nodes to a safe place when the export is finished.

2022-12-13 16:49 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +The export data of the group:
BTW how do we know that the export is done ?

2022-12-13 16:49 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +## Configure Dgraph Alpha server nodes
I would just reference the config page and put it as a pre-req step 
" Before exporting : check that you know the export directories of the alpha server nodes, see <config ref>".

2022-12-13 16:49 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +directory specified through the `--export` flag (defaults to an **export** directory). If any of the groups fail, the entire export process is considered failed and an error is returned.
I would add a section "Attention point".
If one of the Alpha leader does not have enough disk space or encounters an issue, the entire export is considered failed and an error is returned"

2022-12-13 16:49 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +You can export to an S3 or MinIO object store by specifying a URL in the `destination` input field.
We should remove initial reference to MinIO. MinIO is just a way to store to Google or Azure and we will soon remove the need to use MinIO. The feature is to save to Azure Blob Storage and Google Cloud Storage
```suggestion
You can export to an AWS S3, Azure Blob Storage or Google Cloud Storage.
```

2022-12-14 03:03 UTC, Rajakavitha1 commented on content/deploy/dgraph-administration.md
> +## Export database
As a user I would export it from Dgraph to import it else where. However, it is important to list import section in the where to next section. The reason I did not provide the link to import is dont want the user to hop between two guides when performing the action of export.

2022-12-14 03:04 UTC, Rajakavitha1 commented on content/enterprise-features/encryption-at-rest.md
> +You can use [live loader]({{< relref "/deploy/fast-data-loading/live-loader.md" >}}) or [bulk loader]({{< relref "/deploy/fast-data-loading/bulk-loader.md" >}}) to decrypt the data while importing.
Yes!!!! Does not make sense to add a task about things to consider when importing in the export section. I will remove it.

2022-12-14 03:06 UTC, Rajakavitha1 commented on content/howto/exportdata/export-data.md
> +## Configure Dgraph Alpha server nodes
Yes!!! I agree.

2022-12-14 03:08 UTC, Rajakavitha1 commented on content/howto/exportdata/export-data.md
> +The export data of the group:
Good question @MichelDiz  and @rarvikar  Please provide the steps to confirm if the export was successful.

2022-12-14 03:39 UTC, Rajakavitha1 commented on content/enterprise-features/encryption-at-rest.md
> +You can use [live loader]({{< relref "/deploy/fast-data-loading/live-loader.md" >}}) or [bulk loader]({{< relref "/deploy/fast-data-loading/bulk-loader.md" >}}) to decrypt the data while importing.
@rderbier  the only change i made was for the rel ref. We can take this up during the enterprise-feature rewrite.

2022-12-14 05:52 UTC, MichelDiz commented on content/howto/exportdata/export-data.md
> +The export data of the group:
The terminal output will show "export finished" something like this. And there is a GraphQL Query to check the status.

2022-12-14 06:46 UTC, rderbier commented on content/howto/exportdata/export-data.md
> +directory specified through the `--export` flag (defaults to an **export** directory). If any of the groups fail, the entire export process is considered failed and an error is returned.
Action is to verify the disk space I think

2022-12-14 10:30 UTC, Rajakavitha1 commented on content/howto/exportdata/export-data.md
> +directory specified through the `--export` flag (defaults to an **export** directory). If any of the groups fail, the entire export process is considered failed and an error is returned.
done!!

2022-12-14 10:30 UTC, Rajakavitha1 commented on content/howto/exportdata/export-data.md
> +## Configure Dgraph Alpha server nodes
done!!!

2022-12-14 10:30 UTC, Rajakavitha1 commented on content/howto/exportdata/export-data.md
> +The export data of the group:
added the response

2022-12-14 10:30 UTC, Rajakavitha1 commented on content/howto/exportdata/export-data.md
> +*  Specify a list or range of IP addresses allowed to initiate admin operations such as export using the command `dgraph alpha --security whitelist <IP address>`.
removed.

2023-01-12 19:06 UTC, rderbier approved these changes

2023-01-12 19:06 UTC, rderbier commented on content/howto/exportdata/export-data-cloud.md
> +You can also export data from Dgraph Cloud programatically using the Dgraph Cloud API. For more information, see [Cloud API documentation](https://dgraph.io/cloud-docs/blob/master/content/cloud-api/b
```suggestion
You can also export data from Dgraph Cloud programatically using the Dgraph Cloud API. For more information, see [Cloud API documentation](https://dgraph.io/docs/cloud/cloud-api/backup/#export-data).
```

2023-01-13 03:52 UTC, MichelDiz approved these changes

2023-01-13 04:14 UTC, merged