docs(graphql): Update id directive for interfaces (#209)
dgraph-io/dgraph-docs pull request #382
Opened 2022-12-15 03:28 UTC by MichelDiz

Fixes DOC-275

2022-12-15 03:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=382) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=382) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph-docs?pullRequest=382) it.</sub>

2023-04-26 08:15 UTC, mangalaman93 requested changes

2023-04-26 08:15 UTC, mangalaman93 commented on content/graphql/schema/directives/ids.md
> +There are scenarios where this behavior might not be desired, and you may want to constrain the `@id` field to be unique across all the implementing types. In that case, you can set the `interface` a
limit the width of sentence

2023-04-26 08:15 UTC, mangalaman93 commented on content/graphql/schema/directives/ids.md
@rderbier told me that this feature does not work on v23. Do I understand it correctly?

2024-07-26 10:28 UTC, rderbier approved these changes

2024-07-26 10:33 UTC, merged