[docs/revamp] Installation
dgraph-io/dgraph-docs pull request #402
Opened 2023-01-15 12:36 UTC by Rajakavitha1

Addresses: https://github.com/dgraph-io/dgraph-docs/issues/393
Partially addresses: https://github.com/dgraph-io/dgraph-docs/issues/302 

Note: Create and edit docs in the `main` branch when you can, so that we only cherry-pick out of `main`, not into `main`.
-->

2023-01-15 15:19 UTC, MichelDiz approved these changes

2023-01-16 15:03 UTC, darkn3rd commented
While we want to encourage use of Dgraph and synergy across technology, Dgraph officially should NEVER be officially supported on a non-HA environment for production environments.  HA environment means external persistent storage, automatic recovery of failed services, automatic recovery of failed systems (e.g. virtual machines), and highly recommended disaster recovery (backup/restore or export/import with automation).  For development environments, local compiled binaries or containers are fine, leaving the system up to the imagination of the developer.

If we do document single systems for production, this should be in some unofficial or unsupported zone that is clear.

2023-01-16 16:45 UTC, Rajakavitha1 commented
> While we want to encourage use of Dgraph and synergy across technology, Dgraph officially should NEVER be officially supported on a non-HA environment for production environments. HA environment means external persistent storage, automatic recovery of failed services, automatic recovery of failed systems (e.g. virtual machines), and highly recommended disaster recovery (backup/restore or export/import with automation). For development environments, local compiled binaries or containers are fine, leaving the system up to the imagination of the developer.
> 
> If we do document single systems for production, this should be in some unofficial or unsupported zone that is clear.

Hi, @darkn3rd  and @rderbier  could you please use the `suggestions` feature in the GithubUI to make specific changes to the lines that are documented so that it is easy to establish a context and commit the changes to save one more iteration of reviews?

2023-01-16 17:05 UTC, damonfeldman commented on content/installation/single-host-setup.md
> +1. Add a list of IPs allowed for Dgraph so that you can create the schema. Use an     editor of your choice and add the `<IP_ADDRESS>` of the local host in `docker-compose.yml` file:
Is this absolutely necessary to run locally? I don't recall ever doing this, and I think my IP address shifts around due to how my internet provider works. If not, I think we should provide the simplest, fastest way to get started and leave whitelisting for a security guide or best practices somewhere.

2023-01-16 17:06 UTC, damonfeldman commented on content/installation/single-host-setup.md
> +        command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=<IPADDRESS>
underscore missing in IP_ADDRESS (matters because when I search for it, I can't find it in the config file)

2023-01-16 18:06 UTC, MichelDiz requested changes

2023-01-16 18:06 UTC, MichelDiz commented on content/installation/single-host-setup.md
> +You can install and run Dgraph servers on a single host using Docker, Docker Compose, or Dgraph command line.
Let's remove the term "servers" or "server" from Docs. Use "Cluster" instead. Dgraph "server" is a compound of multiple instances/nodes. The Alphas "serves" data, but they aren't a "server" per se. A server in IT is a machine that serves some service.

If we use "Cluster" everywhere it will make clear to the user that Dgraph works with clustering manner.

2023-01-16 18:10 UTC, MichelDiz commented on content/installation/single-host-setup.md
> +1. Add a list of IPs allowed for Dgraph so that you can create the schema. Use an     editor of your choice and add the `<IP_ADDRESS>` of the local host in `docker-compose.yml` file:
@damonfeldman 127.0.0.1 will always be localhost. The ISP doesn't have any control of this. So it will never change as it is a local context.

About whitelisting. This is necessery for some cases. e.g if you wanna expose Dgraph to a subnet, or make it available only for Docker networking and not from outside Docker.

2023-01-16 23:55 UTC, rderbier requested changes

2023-01-16 23:55 UTC, rderbier commented on content/installation/download.md
> +listed above. You can also use https://play.dgraph.io/ to run Ratel.
This is wrong. Ratel is no more distributed with Dgraph releases.
```suggestion
```

2023-01-16 23:55 UTC, rderbier commented on content/installation/kubernetes.md
> +title = "Kubernetes"
I think we should have the page named "HA Cluster Setup Using Kubernetes" and set under "Production environment setup".
-> check with Joaquin if single server setup with K8s makes sense.
I suggest we move also the Metrics part is a separate page (under Production environment setup) "Monitoring" -> see with Joaquin and Matthew.

2023-01-17 08:12 UTC, Rajakavitha1 commented on content/installation/single-host-setup.md
> +       mkdir ~/<ZERO> # Or any other directory where data should be stored.
done!!! changes to < ZERO_DATA>,<ALPHA_DATA_1>, <ALPHA_DATA_2>

2023-01-17 08:12 UTC, Rajakavitha1 commented on content/installation/single-host-setup.md
> +        command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=<IPADDRESS>
done!!! fixed

2023-01-17 08:13 UTC, Rajakavitha1 commented on content/installation/single-host-setup.md
> +You can install and run Dgraph servers on a single host using Docker, Docker Compose, or Dgraph command line.
Changed it to cluster. The only references to Server are when we are referring to the actual UI test in Ratel. I cant change that.

2023-01-17 08:21 UTC, Rajakavitha1 commented
> I reviewed the sections I understand, but don't think I'm expert enough to weigh in on k8s or docker swarm.

Thanks for the review @damonfeldman !!! the k8s and docker swarm sections are only moved to the install directory in the new IA. Those need a rewrite as well.

2023-01-17 08:27 UTC, Rajakavitha1 commented on content/_index.md
> +    <p><b>Tip</b>: New to Dgraph? Take the <a href="https://dgraph.io/tour">Dgraph Tour</a> to run live queries in your browser. Then, try Dgraph as a <a href="https://cloud.dgraph.io">cloud service<
done!!!

2023-01-17 08:37 UTC, Rajakavitha1 commented on content/installation/kubernetes.md
>  The following section covers running Dgraph with Kubernetes. We have tested Dgraph with Kubernetes versions 1.14 to 1.16 on [GKE](https://cloud.google.com/kubernetes-engine) and versions 1.14 to 1.17
This was only a IA move not a content rewrite. We can take this up in a new PR.

2023-01-17 08:38 UTC, Rajakavitha1 commented on content/installation/multi-host-setup.md
>  ## Using Docker Swarm
This was only a IA move not a content rewrite. We can take this up in a new PR.

2023-01-17 08:42 UTC, Rajakavitha1 commented on content/installation/single-host-setup.md
> +    parent = "installation"
We do not want a nested IA that would make the search difficult. The higher the content the better. We can address the dev and production in the introduction of the content or in the landing page here: https://dgraph.io/docs with links to the respective pages.

2023-01-17 15:17 UTC, damonfeldman approved these changes
Some <IP/VARS> used but not defined, or defined and not used.

2023-01-17 15:17 UTC, damonfeldman commented on content/installation/single-host-setup.md
> +       docker run -it -p 5080:5080 --network <DGRAPH_NETWORK> -p 6080:6080 -v ~/zero:/dgraph dgraph/dgraph:{{< version >}} dgraph zero --my=<IP_ADDRESS>:5080
Should use <ZERO_DATA> in here like <DGRAPH_NETWORK>

2023-01-17 15:17 UTC, damonfeldman commented on content/installation/single-host-setup.md
> +       docker run -it -p 7081:7081 --network <DGRAPH_NETWORK> -p 8081:8081 -p 9081:9081 -v ~/<ALPHA_DATA_2>:/dgraph dgraph/dgraph:{{< version >}} dgraph alpha --zero=HOSTIPADDR:5080 --my=<IP_ADDRESS>
Looks like we mean to have a <HOSTIPADDR> (or HOST_IP_ADDR?) defined above, and if so should put in angle brackets for consistency.

2023-01-17 15:17 UTC, damonfeldman commented on content/installation/single-host-setup.md
> +     docker run -it -p 7080:7080 --network <DGRAPH_NETWORK> -p 8080:8080 -p 9080:9080 -v ~/<ALPHA_DATA_1>:/dgraph dgraph/dgraph:{{< version >}} dgraph alpha --zero=HOSTIPADDR:5080 --my=<IP_ADDRESS>:7
Looks like we mean to define and use <HOST_IP_ADDR> and use in angle brackets.

2023-01-17 16:22 UTC, Rajakavitha1 commented on content/installation/single-host-setup.md
> +     docker run -it -p 7080:7080 --network <DGRAPH_NETWORK> -p 8080:8080 -p 9080:9080 -v ~/<ALPHA_DATA_1>:/dgraph dgraph/dgraph:{{< version >}} dgraph alpha --zero=HOSTIPADDR:5080 --my=<IP_ADDRESS>:7
I am sorry that I had missed this it is <IP_ADDRESS> and is already defined in the before you begin

2023-01-17 16:22 UTC, Rajakavitha1 commented on content/installation/single-host-setup.md
> +       docker run -it -p 7081:7081 --network <DGRAPH_NETWORK> -p 8081:8081 -p 9081:9081 -v ~/<ALPHA_DATA_2>:/dgraph dgraph/dgraph:{{< version >}} dgraph alpha --zero=HOSTIPADDR:5080 --my=<IP_ADDRESS>
fixed

2023-01-17 16:22 UTC, Rajakavitha1 commented on content/installation/single-host-setup.md
> +       docker run -it -p 5080:5080 --network <DGRAPH_NETWORK> -p 6080:6080 -v ~/zero:/dgraph dgraph/dgraph:{{< version >}} dgraph zero --my=<IP_ADDRESS>:5080
fixed

2023-01-18 02:14 UTC, rderbier approved these changes

2023-01-18 02:14 UTC, rderbier commented on content/installation/single-host-setup.md
> +title = "Single Host Setup"
I suggest we merge this with the clarification on about cluster setup and we do a new PR to add the standalone option for easy setup of a dev env with a single alpha (no cluster).

2023-01-18 02:14 UTC, rderbier commented on content/installation/download.md
> +You can also build [Dgraph](https://github.com/dgraph-io/dgraph/blob/master/CONTRIBUTING.md) and [Ratel UI](https://github.com/dgraph-io/ratel/blob/master/INSTRUCTIONS.md) from source.
```suggestion
You can also build **Dgraph** and **Ratel UI** from the source code by following the instructions from [Contributing to Dgraph](https://github.com/dgraph-io/dgraph/blob/master/CONTRIBUTING.md) or [Building and running ratel](https://github.com/dgraph-io/ratel/blob/master/INSTRUCTIONS.md).
```

I found the link not obvious with just the product name. I initially thought that the links were just the links to the product and that the sentence was not telling me how to proceed.

2023-01-18 05:28 UTC, rderbier approved these changes

2023-01-18 05:31 UTC, MichelDiz approved these changes

2023-01-18 05:31 UTC, MichelDiz commented on content/installation/_index.md
> +      This section is about installing Dgraph in dev or hobbyist environment as well as production environments with HA and  horizontal scalability using multiple servers in a cluster.
"horizontal scalability using multiple Alpha nodes in a cluster."

2023-01-18 05:31 UTC, MichelDiz commented on content/installation/single-host-setup.md
> +1. In the **Dgraph Server Connection** dialog that set the **Dgraph server URL** as `http://<CLOUD_IP_ADDRESS>:8080`
I have a PR changing this. Not sure if we change it now and end up forgetting about it. The name changing took a long time to be noticed everywhere.

See the PR https://github.com/dgraph-io/ratel/pull/289

I will not be a blocker here. But we need to change it.

2023-01-18 05:57 UTC, merged