revamp/ install production
dgraph-io/dgraph-docs pull request #439
Opened 2023-02-02 03:47 UTC by Rajakavitha1

Rewrite the install sections based on the discussion here: https://docs.google.com/document/d/1aqYDpJedSGXTw8iciYQVtna9wtTvtdmgSKsxfVmU5U0/edit#

2023-02-13 19:45 UTC, rderbier approved these changes

2023-02-13 19:45 UTC, rderbier commented on content/installation/production-checklist.md
> +
```suggestion
This guide describes important setup recommendations for a production-ready Dgraph cluster, ensuring high availability with external persistent storage, automatic recovery of failed services, automatic recovery of failed systems such as virtual machines, and disaster recovery such as backup/restore or export/import with automation.

```

2023-02-13 19:45 UTC, rderbier commented on content/installation/single-host-setup.md
> +### Install Dgraph
```suggestion

```
we have a section "production checklist" with this.
The page is about installing a learning env. No need for this extra title imo.

2023-02-13 19:45 UTC, rderbier commented on content/installation/single-host-setup.md
>  To setup a Dgraph cluster on a single host using Docker:
Add a section on standalone.
Rename section Using Docker ->  Setup a Dgraph cluster on a single host using Docker
```suggestion
#### Launch a Dgraph standalone cluster using Docker
1.  Select a name `<CONTAINER_NAME>` for you Docker container and create a directory `<GRAPH_DATA_PATH>` that will hold the Dgraph data on your local file system.
1.  Run a container with the dgraph/standalone image:
    ```sh
       docker run --name <CONTAINER_NAME> -d -p "8080:8080" -p "9080:9080" -v <DGRAPH_DATA_PATH>:/dgraph dgraph/standalone:latest
    ```
1. Optionaly launch [Ratel UI]({{< relref "ratel/overview.md" >}}) using the dgraph/ratel docker image :
    ``` sh
    docker run --name ratel  -d -p "8000:8000"  dgraph/ratel:latest
    ```
You can now use Ratel UI on your browser at localhost:8000 and connect to you Dgraph cluster at localhost:8080
#### Setup a Dgraph cluster on a single host using Docker

2023-02-14 16:18 UTC, damonfeldman requested changes

2023-02-14 16:18 UTC, damonfeldman commented on content/installation/production-checklist.md
> +To ensure that Dgraph can take full advantage of machine resources, we recommend each Dgraph instance to be deployed to a single dedicated machine to ensure that Dgraph can take full advantage of mac
```suggestion
To ensure that Dgraph is highly-available, we recommend each Dgraph instance be deployed to a different underlying host machine, and ideally that machines are in different availability zones or racks. In the event of an underlying machine failure, it is critical that only one Dgraph alpha and one Dgraph zero be offline so that 2 of the 3 instances in each group maintain a quorum. Also when using VMs or Docker/K8s, ensure machines are not over-subscribed and ideally not co-resident with other processes that will interrupt and delay Dgraph processing.
```

2023-02-14 16:18 UTC, damonfeldman commented on content/installation/production-checklist.md
> +At a the bare minimum, we recommend machines with at least 8 CPUs and 16 GiB of memory for testing.
```suggestion

We recommend 8 vCPUs or cores on each of three HA alpha instances for production loads, with 16 GiB+ memory per node.
```

2023-02-14 16:18 UTC, damonfeldman commented on content/installation/production-checklist.md
> +At a the bare minimum, we recommend machines with at least 8 CPUs and 16 GiB of memory for testing.
Note we provision 2 vCPU clusters in our cloud offering, but recommend 8 vCPU for prod. We do not seem to require 3x HA instances for prod, but probably should.

2023-02-14 16:18 UTC, damonfeldman commented on content/installation/production-checklist.md
> +To ensure that Dgraph can take full advantage of machine resources, we recommend each Dgraph instance to be deployed to a single dedicated machine to ensure that Dgraph can take full advantage of mac
Note our own cloud infrastructure puts many pods on the same EC2 instance, but we ensure they are not over-subscribed. These days with docker, I think that's going to be common, vs dedicated physical or EC2 machines.

2023-02-14 16:18 UTC, damonfeldman commented on content/installation/kubernetes/cluster-types.md
> +An **N-node cluster** is a Dgraph cluster that contains N number of Dgraph instances. For example, a 6-node cluster means six Dgraph instances. The **replication setting** specifies the number of Dgr
```suggestion
An **N-node cluster** is a Dgraph cluster that contains N number of Dgraph instances. For example, a 6-node cluster means six Dgraph instances. The **replication setting** specifies the number of Dgraph Alpha replicas that are in each group. If this is higher than 1, each alpha in a group will hold a full copy of that group's data. The replication setting is a configuration flag (`--replicas`) on Dgraph Zero. Sharding is done (typically for databases near 1TB in size) by creating multiple **Dgraph Alpha groups**.  Every Dgraph Alpha group is automatically assigned a set of distinct predicates to store and serve, thus dividing up the data.
```

2023-02-14 16:18 UTC, damonfeldman commented on content/installation/kubernetes/cluster-types.md
> +An **N-node cluster** is a Dgraph cluster that contains N number of Dgraph instances. For example, a 6-node cluster means six Dgraph instances. The **replication setting** specifies the number of Dgr
Technically, a group may hold one replica, so different groups do not imply replication. It's important to node that a group is a shard.

2023-02-24 14:40 UTC, damonfeldman approved these changes

2023-02-24 16:04 UTC, merged