Docs(Overview): Add a high-level overview that covers ways customers can use Dgraph (self-managed or fully-managed) and provides a glossary of terms.
dgraph-io/dgraph-docs pull request #45
Opened 2021-02-05 22:53 UTC by aaroncarey

Cherry-pick to 20.11, 20.07 and 20.03

2021-02-05 23:40 UTC, danielmai requested changes
Added some suggested edits. Let's update the use cases in the intro.

And, I think this should have its own card on the docs home page (e.g., https;//dgraph.io/docs). What do you think?

2021-02-05 23:40 UTC, danielmai commented on content/dgraph_overview.md
> +* Real-time chat applications
This list should be reordered by some scheme (like popularity). It's also missing use cases like data unification, customer 360, entity resolution, and master data management.

2021-02-05 23:40 UTC, danielmai commented on content/dgraph_overview.md
> +infrastructure. You can also run Dgraph in your AWS, GCP or Azure cloud
```suggestion
infrastructure. You can also run Dgraph in your AWS, GCP, or Azure cloud
```
serial comma ([style guide](https://discuss.dgraph.io/t/dgraph-developer-documentation-style-guide/10955#formatting-punctuation-and-organization))

2021-02-05 23:40 UTC, danielmai commented on content/dgraph_overview.md
> +You can get started using Slash GraphQL today with a free trial [Try Slash GraphQL](https://slash.dgraph.io/).
```suggestion
You can [get started using Slash GraphQL today](https://slash.dgraph.io) with a free trial.
```

2021-02-05 23:40 UTC, danielmai commented on content/dgraph_overview.md
> +To use Dgraph Cloud, visit the [Dgraph Pricing Page](https://dgraph.io/pricing) to
If you intend for these to be two separate paragraphs, a newline is needed between the Slash GraphQL and Dgraph Cloud sentences. Otherwise, it's the same paragraph.

2021-02-05 23:40 UTC, danielmai commented on content/dgraph_overview.md
> +Slash gives you the power of Dgraph database in a hosted environment, giving you
```suggestion
Slash GraphQL gives you the power of Dgraph database in a hosted environment, giving you
```

2021-02-05 23:40 UTC, danielmai commented on content/dgraph_overview.md
> +Dgraph Cloud extends Slash GraphQL to meet the needs of enterprise customers.
```suggestion
Dgraph Cloud extends Slash GraphQL to meet the needs of enterprise customers with dedicated instances, high availability, and the choice of running in your own cloud VPC.
```

2021-02-05 23:40 UTC, danielmai commented on content/dgraph_overview.md
> +[Deploy](/deploy) section).
```suggestion
[Deploy]({{< relref "/deploy" >}}) section).
```
I _think_ this needs to be a [relref](https://gohugo.io/functions/relref/), or else this link itself is relative to the hostname (e.g., `dgraph.io/deploy` instead of `dgraph.io/docs/deploy` (or a specific version like /docs/v20.11).

All the docs links in this file would need to be relrefs.

2021-02-05 23:40 UTC, danielmai commented on content/dgraph_overview.md
> +backend.  Dgraph is built for the heavy transactional workloads required to
```suggestion
backend. Dgraph is built for the heavy transactional workloads required to 
```

2021-02-05 23:40 UTC, danielmai commented on content/dgraph_overview.md
> +power modern apps and websites,  but it isn’t limited to only these types of
```suggestion
power modern apps and websites, but it isn’t limited to only these types of
```

2021-02-07 01:07 UTC, aaroncarey commented on content/dgraph_overview.md
> +[Deploy](/deploy) section).
OK, I'll make this change throughout :)

2021-02-07 01:07 UTC, aaroncarey commented
> Added some suggested edits. Let's update the use cases in the intro.
> 
> And, I think this should have its own card on the docs home page (e.g., https;//dgraph.io/docs). What do you think?

Agreed; I'll add a card on the landing page to this PR :)

2021-02-07 01:14 UTC, aaroncarey commented on content/dgraph_overview.md
> +* Real-time chat applications
Thanks! I added the ones that you mentioned and alphabetized the list. We probably should re-order this list by popularity; I'll look into this.

2021-02-07 01:32 UTC, aaroncarey commented on content/dgraph_overview.md
> +To use Dgraph Cloud, visit the [Dgraph Pricing Page](https://dgraph.io/pricing) to
Thanks for checking; the intent was to keep these in the same paragraph.

2021-02-07 01:34 UTC, aaroncarey commented
I still need to add a link to this from the landing page (a card), and follow-up about the ordering of the use case list at the top of the page.

2021-02-08 13:18 UTC, bucanero commented
> I still need to add a link to this from the landing page (a card), and follow-up about the ordering of the use case list at the top of the page.

if you need help adding the card to the home page, let me know 👍

2021-02-08 23:01 UTC, aaroncarey commented on content/dgraph_overview.md
> +* Real-time chat applications
> > I still need to add a link to this from the landing page (a card), and follow-up about the ordering of the use case list at the top of the page.
> 
> if you need help adding the card to the home page, let me know 👍

Thanks for adding the card! :)

2021-02-09 12:12 UTC, bucanero approved these changes

2021-02-12 16:04 UTC, moonstormer approved these changes
Really great work! Just a couple minor changes/links

2021-02-12 16:04 UTC, moonstormer commented on content/dgraph_overview.md
> +* Self-managed: You can use Dgraph on-premises, hosted on your own physical
Let's link this reference to Dgraph to the product page: dgraph.io/dgraph

2021-02-12 16:04 UTC, moonstormer commented on content/dgraph_overview.md
> + Slash GraphQL gives you the power of Dgraph in a hosted service. Dgraph Cloud
Let's link this mention of Slash to the Slash product page, and the mention of Dgrahp Cloud to the Cloud product page. :)

2021-02-12 18:15 UTC, aaroncarey commented on content/dgraph_overview.md
> +specific scenarios by reading
Done :)

2021-02-12 18:16 UTC, aaroncarey commented on content/dgraph_overview.md
> +* Data unification
Done :)

2021-02-12 18:21 UTC, aaroncarey commented on content/dgraph_overview.md
> +**Note**: The documentation provided on this site (dgraph.io/docs) is applicable
Agreed that this shouldn't be an unliked hyperlink. I made a change similar to your suggestion :)

2021-02-12 18:22 UTC, aaroncarey commented on content/dgraph_overview.md
> +* Self-managed: You can use Dgraph on-premises, hosted on your own physical
Done

2021-02-12 18:25 UTC, aaroncarey commented on content/dgraph_overview.md
> + Slash GraphQL gives you the power of Dgraph in a hosted service. Dgraph Cloud
Done :)

2021-02-13 00:43 UTC, merged