Docs(Deployment and Management): Add a high-level overview, reorganize this section, add sub-section
dgraph-io/dgraph-docs pull request #47
Opened 2021-02-09 07:43 UTC by aaroncarey

Per feedback from various core team members, the "deploy" section of the left nav has too many topics to be easy for users to navigate. This PR makes the following changes:
- Adds an overview topic to the section, that clarifies that this section applies to self-managed Dgraph (on-prem or in the user's cloud infra) and that clearly defines Dgraph Alpha and Dgraph Zero.
- Adds an "Administration" sub-section, and a "Security" sub-section

After this PR, a follow-up PR will add a "Dgraph CLI Reference" that we can use to document undocumented CLI commands.

Fixes DOC-23

2021-02-09 12:43 UTC, bucanero reviewed
Just an idea, I’d actually make the `Administration` section a top-level one; e.g.:

- Clients
- Ratel UI
- Deploy
- **Administration** 
- Enterprise features

`Security` could remain under the `Deploy` section

2021-02-09 17:43 UTC, aaroncarey commented
> Just an idea, I’d actually make the `Administration` section a top-level one; e.g.:
> 
>     * Clients
> 
>     * Ratel UI
> 
>     * Deploy
> 
>     * **Administration**
> 
>     * Enterprise features
> 

Thanks for your feedback! My worry with this change is that these administrative tasks are more around the administration of the server nodes, rather than the administration of the data. As a reader, I'd expect a top-level administration section to mostly focus on managing data, schema, and access to data. So, I'd rather leave this section under "deploy and manage", so that we can keep content that is specific to self-managed deployment scenarios grouped together.

2021-02-15 13:58 UTC, OmarAyo commented on content/deploy/overview.md
> +Dgraph runs on two types of server nodes, even when you are doing a proof-of-concept
> Dgraph runs on two types of server nodes,

Seems a bit confusing to me, I'd rather say:

```
Dgraph consist of at least 2 nodes (6 nodes for HA)
```
Or something similar

2021-02-15 13:59 UTC, OmarAyo commented on content/deploy/overview.md
> +* Dgraph Alpha database server: The Dgraph Alpha server nodes in your deployment host and serve data. These nodes also host an `/admin` HTTP and GRPC endpoint that can
I would use the word `node` instead of server

2021-02-15 13:59 UTC, OmarAyo commented on content/deploy/overview.md
> +* Dgraph Zero management server: The Dgraph Zero nodes in your deployment control
I would use the word node instead of server

2021-02-15 14:01 UTC, OmarAyo commented on content/deploy/production-checklist.md
> +For Dgraph, backups are created using the [backups enterprise feature]({{< relref "/enterprise-features/binary-backups" >}}). You can also create full backups of your data and schema using [data expo
> You can also create full backups of your data 

As we say that the backups are ee feature, I would replace the word backup with export:

```
You can also create exports of your data and schema
```

2021-02-15 14:02 UTC, OmarAyo requested changes
after addressing comments, LGTM

2021-02-17 06:58 UTC, aaroncarey commented on content/deploy/overview.md
> +* Dgraph Alpha database server: The Dgraph Alpha server nodes in your deployment host and serve data. These nodes also host an `/admin` HTTP and GRPC endpoint that can
I'd rather write this out as "server node" on first mention; agreed that "node" should be in the first reference.

2021-02-17 07:25 UTC, aaroncarey commented on content/deploy/overview.md
> +* Dgraph Zero management server: The Dgraph Zero nodes in your deployment control
Per the previous comment, let's go with "server nodes" on this page, where we are defining these terms in-context for the first time. Our use of "node" elsewhere to mean data object means we should be careful to specify "server node". Agreed that introducing this as "Dgraph Zero management server" instead of "Dgraph Zero management server nodes" risks confusing readers. Please take a look at the revision, which I think addresses your concerns.

2021-02-17 07:27 UTC, aaroncarey commented on content/deploy/production-checklist.md
> +For Dgraph, backups are created using the [backups enterprise feature]({{< relref "/enterprise-features/binary-backups" >}}). You can also create full backups of your data and schema using [data expo
Fixed.

2021-02-17 07:41 UTC, aaroncarey commented on content/deploy/overview.md
> +Dgraph runs on two types of server nodes, even when you are doing a proof-of-concept
I rewrote this to simplify it to "A Dgraph cluster consists of the following:"

I added the information about two-node and six-node deployments to a revised section after the bullets defining each node.

2021-02-17 12:56 UTC, OmarAyo approved these changes
LGTM

2021-02-19 10:54 UTC, merged