cleam json mutation document
dgraph-io/dgraph-docs pull request #479
Opened 2023-02-22 22:30 UTC by rderbier

remove reference to RDF.
Remove explanation aout curl and HTTP client.

Clarify JSON examples.

2023-02-23 02:47 UTC, Rajakavitha1 requested changes

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +## Forbidden values
Do we need this heading? we don't seem to have an intro paragraph

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +To create a predicate as a list of string :
```suggestion
To create a predicate as a list of string:
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +To add a value :
```suggestion
To add a value:
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +When using JSON format Dgraph creates nodes and relationships from the JSON structure and handles the assignation of UIDs to nodes.
```suggestion
When using JSON format Dgraph creates nodes and relationships from the JSON structure and assigns UIDs to nodes.
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +For example, if you run the following mutation
```suggestion
For example, if you run this mutation: 
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +You can control the identifier name by specifying a `uid` field in your JSON data and using the notation :
```suggestion
You can control the identifier name by specifying a `uid` field in your JSON data and using the notation: 
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +In the following mutation we are using two JSON objects but as they are refering to the same identifier, Dgraph creates only one node :
```suggestion
In this mutation, there are two JSON objects and because they are referring to the same identifier, Dgraph creates only one node :
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +Running this mutation, you can see that Dgraph returns the UID of the created node with the `diggy` identifier :
```suggestion
When you run this mutation, you can see that Dgraph returns the UID of the node that was created with the `diggy` identifier:
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +Will add the specie information to the node we have created earlier.
```suggestion
Adds the `specie` information to the node that was created earlier.
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +Assuming that `specie` predicate has the @lang directive, the JSON mutation
```suggestion
In case, `specie` predicate has the @lang directive, the JSON mutation
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +Will set the `specie` string predficate in two english and in french.
```suggestion
Dgraph sets the `specie` string predicate in English and in French.
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +Will result in the creation of three nodes and the `food` predicate will be a relationship.
```suggestion
This result in the creation of three nodes and the `food` predicate as a relationship.
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +To delete all predicates of a given node :
```suggestion
To delete all predicates of a given node:
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +- run a delete mutation specifying only the uid field :
```suggestion
- run a delete mutation specifying only the uid field
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +To delete a Facet, overwrite it :  when you run a mutation for the same entity without a facet, the existing facet will be deleted automatically.
```suggestion
To delete a `Facet`, overwrite it. When you run a mutation for the same entity without a `Facet`, the existing `Facet` is deleted automatically.
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +Assuming `0x06` is the UID of the node created.
```suggestion
For example, if  `0x06` is the UID of the node created.
```

2023-02-23 02:47 UTC, Rajakavitha1 commented on content/dql-syntax/json-mutation-format.md
> +To remove one value from the list :
```suggestion
To remove one value from the list:
```

2023-02-23 17:48 UTC, rderbier commented on content/dql-syntax/json-mutation-format.md
> +## Forbidden values
I moved the section at the end and named it "reserved values". We must mention it somewhere.

2023-02-26 07:49 UTC, Rajakavitha1 approved these changes

2023-03-02 15:46 UTC, merged