initial rework of concepts area
dgraph-io/dgraph-docs pull request #495
Opened 2023-03-01 00:37 UTC by damonfeldman

This is a rework of the "Design Concepts" area of the docs. 

New terminology was used.
Where there were TODOs or "obsolete" comments, text was added.
General read-through and rewrite.
Some technical detail (internal go data structures) were removed

Note data is not broken up into one file per concept yet, and links are sparse to related concepts.

2023-03-01 00:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=495) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=495) before we can accept your contribution.<br/><hr/>**Damon** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph-docs?pullRequest=495) it.</sub>

2023-03-01 16:33 UTC, rderbier requested changes

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +queries in that direction, they would need to define the [reverse relationship]({{< relref "predicate-types.md#reverse-edges" >}})
Suggest to remove this part.
Relationship is already explained in the glossary.
And RDF has a page in DQL > Syntax.
If the RDF page is not clear enough then we should update the RDF page.
note : we can move the RDF page to Concpets folder if it makes sense later.
``

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +Dgraph groups all relationships of a given type together into one data structure called a `tablet`. E.g. in a database of people who are friends with one another, and have first names and last names,
could we explain why a user may have to know what is a posting list ?
Something in the line of "Cretain administrative tasks requires the understanding of tablets and posting lists" or anything that could tell me why I should be interested.

The point is to avoid the "it's too complex' effect for first readers. If I see that it is for Admin task I can skip that whitout telling me " yet another stuff that I have not heard of inside Dgraph ... it's very complex ..."

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +queries in that direction, they would need to define the [reverse relationship]({{< relref "predicate-types.md#reverse-edges" >}})
```
```

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
>  as part of the schema.{{% /notice %}}
```suggestion
```

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +Internally, the RDF N-Quad is represented in one of two ways:
```suggestion

```

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +For `Relationships`, the subject and object are represented as 64-bit numeric UIDs and the relationship name itself links them: <subjectUID> <relationshipName> <objectUID>.
```suggestion

```

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +For literal attributes of a `Node`, the subject must still (and always) be a numeric UID, but the Object will be a primitive value. These can be thought of as <subjectUID> <relationshipName> <value>,
```suggestion
```

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +[Badger](https://github.com/dgraph-io/badger) is a key-value store developed and maintained by Dgraph. It is also open source, and it is the backing store for Dgraph data.
```suggestion
```

Bdger is explained in the Glossary.
 I would mention Badger in the Dgraph Architceture document. It's not a key concept for Dgraph users imo but a key component of the Architecture

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
>  ##  Badger
```suggestion
```

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +Badger values are `Posting Lists` and indexes. Badger Keys are formed by concatenating <RelationshipName>+<NodeUID>.
```suggestion
```
To put in Architecture doc if it makes sense

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +A `Group` in Dgraph is a shard of data, and may or may not be highly-available (HA). An HA group typically has three Dgraph instances (servers or K8s pods), and a non-HA group is a single instance. E
Delete Group section from here. and add info in dgraph-overview/#scale-replication-and-sharding

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +In a future version, if a tablet gets too big, it will be split among two groups, but currently data is balanced by moving each tablet to one group only.
```suggestion
```
It's a doc, not a roadmap ! But all section should be removed anyway.

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
Change the title title = "Concepts"
After some cleaning it looks like this page is more about 'Architectural concepts' maybe ?
Or split it in several pages as you suggested.

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
>  ## Queries
```suggestion
## Query execution
```
But I don't think we need this section at all.

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
>  ## Protocol Buffers
un-necessary section

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +## DQL
to remove and update DQL page if needed. https://dgraph.io/docs/dql/

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +## GraphQL
remove the section.
Add info if needed to https://dgraph.io/docs/graphql/

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +## Dgraph Clients
remove and put info if necessary in 
https://dgraph.io/docs/clients/

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +## Dgraph Ratel GUI
remove and put info if needed in Ratel Page

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +
```suggestion

```

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +## ACLs
remove and add info if needed to https://dgraph.io/docs/enterprise-features/access-control-lists/

2023-03-01 16:33 UTC, rderbier commented on content/design-concepts/concepts.md
> +## Lambdas
probably to move in GraphQL or Architecture overview. not really a concept

2023-03-27 23:59 UTC, rderbier approved these changes
Please correct the info about RDF on queries. It is a feature.

2023-03-27 23:59 UTC, rderbier commented on content/design-concepts/minimizing-network-calls.md
> +<sup>*</sup> _Throughout this note, we call entities in a graph "nodes" which is a standard terminology when talking about nodes and predicates. Elsewhere we call nodes "entities" to avoid confusion
```suggestion
```
elsewhere we use "nodes"

2023-03-27 23:59 UTC, rderbier commented on content/design-concepts/acl-concept.md
> +title = "ACLs (concept)"
```suggestion
title = "ACLs"
```

2023-03-27 23:59 UTC, rderbier commented on content/dgraph-glossary.md
> +Dgraph Query Language is Dgraph's proprietary language to insert, update, delete and query data. It is based on GraphQL, but is more expressive. (See also: [GraphQL](#GraphQL))
I dont' think "It is based on GraphQL, but is more expressive. (See also: [GraphQL](#GraphQL))"
adds to the understanding.

How does telling that DQL is based on GraphQL help the user? If he believes that knowing GraphQL is enough to use DQL it is misleading and then it is opening a bunch of question of why is it different.

I think it helps to just say we have DQL and GraphQL so we don't have to justify why DQL is different.
DQL is to query our DB, GraphQL is to specify and serve a GraphQL API.
```suggestion
Dgraph Query Language is Dgraph's proprietary language to insert, update, delete and query data.```

2023-03-27 23:59 UTC, rderbier commented on content/dql-syntax/dql-rdf.md
> +Dgrpah supports Resource Description Framework (RDF) when creating, importing and exporting data. Queries always return JSON at this time.
this is wrong. When using the clients you can ask to return RDF.
```suggestion
Dgrpah supports Resource Description Framework (RDF) when creating, importing and exporting data.
```

2023-03-30 14:53 UTC, damonfeldman commented on content/design-concepts/acl-concept.md
> +title = "ACLs (concept)"
To avoid collisions with full documentation areas, I've added "(concept)" to the concept docs. We may also have a section on "Dgraph ACLs" vs the overall concept of ACLs which is a standard industry "concept."

2023-03-30 14:56 UTC, damonfeldman commented on content/dgraph-glossary.md
> +Dgraph Query Language is Dgraph's proprietary language to insert, update, delete and query data. It is based on GraphQL, but is more expressive. (See also: [GraphQL](#GraphQL))
It is based on it, though (DQL was originally GraphQL+/- right?). And the key elements of being declarative, and generally being a template for the JSON you'll get back is the same. Perhaps the key thing is that if you know GraphQL you have a big leg up on DQL, but would have no idea at all how to do Cypher or Gopher etc.

2023-03-30 15:58 UTC, damonfeldman commented on content/design-concepts/concepts.md
I think this was removed when I did a merge, which is good. The concepts are now all broken out.

2023-03-31 01:03 UTC, merged