docs(trace): Add example of tags to be used in jaeger
dgraph-io/dgraph-docs pull request #502
Opened 2023-03-02 23:43 UTC by MichelDiz

2023-03-03 20:54 UTC, damonfeldman requested changes

2023-03-03 20:54 UTC, damonfeldman commented on content/deploy/tracing.md
> +
The OpenTrace information collected by Dgraph and displayed in Jaeger contains various messages and metadata that can also be filtered by tag. Below is a list of information that is in Jaeger as a tag.

2023-03-03 20:54 UTC, damonfeldman commented on content/deploy/tracing.md
> +This tag you will filter out based on error status.
I think we should give a little more info on what the tag would match. Doing a quick search for "error" annotations I only find it in otrace.Attribute{otrace.BoolAttribute("error", true)} in oracle.go::428, so I think we can say that this will find transactions that encountered an error during the commit operation (vs other internal errors).

2023-03-03 20:54 UTC, damonfeldman commented on content/deploy/tracing.md
> +This tag you will filter out based on status code 0, 1 or 2.
Do we know what this code means?

2023-03-03 20:54 UTC, damonfeldman commented on content/deploy/tracing.md
> +handleHasFunction, n.proposeAndWait, dgraph.Execute, resolveMutation,
I pasted a bunch of these in Jaeger, but did not get results. Is there a particular syntax needed? We should say more about these, such as that certain ones mean a particular thing, or that generally you can go search the code for these to see what they capture.

2023-03-04 18:12 UTC, MichelDiz commented on content/deploy/tracing.md
> +
Is that a suggestion of a text to introduce or are you just commenting?

2023-03-04 18:16 UTC, MichelDiz commented on content/deploy/tracing.md
> +This tag you will filter out based on error status.
Yeah, This text can be expanded. It is humanly impossible to explain what each tag does and why at the moment. It was hard to find the ones that works. All of those I've tested on my end.

BTW, several messages are random. So I've skipped a bunch of them. They have random IDs, random timestamps, random errors, erros based on predicate(which can be any). So I have added only those who doesn't change over time.

But to explain them I think this is a more deep research. This PR is just a beginning.

2023-03-04 18:17 UTC, MichelDiz commented on content/deploy/tracing.md
> +This tag you will filter out based on status code 0, 1 or 2.
it is based on unix signals. Shell based I mean. 0 mean successful, 1 and 2 are errors. 2 is in general a panic or something.

2023-03-04 18:20 UTC, MichelDiz commented on content/deploy/tracing.md
> +handleHasFunction, n.proposeAndWait, dgraph.Execute, resolveMutation,
Nothing special. You need to run a query in order to see. For example, run a has function and then add this tag
funcName=handleHasFunction

But you have to set to all Operation. Don't filter by operation. Or filter by query.

2024-07-26 01:50 UTC, closed without merging