Docs(loader): Improve bulk loader's description
dgraph-io/dgraph-docs pull request #55
Opened 2021-02-12 13:21 UTC by bucanero

Fix DOC-41

2021-02-15 13:48 UTC, OmarAyo commented on content/deploy/fast-data-loading/bulk-loader.md
> +![Bulk Loader diagram](/images/deploy/bulk-loader.png)
Two notes:

1. If you really want to add the diagram I suggest you add it after line 155
2. I suggest you reach out to our designer to convert the diagram to something better looking

2021-02-15 13:51 UTC, OmarAyo commented on content/deploy/fast-data-loading/bulk-loader.md
> +{{% /notice %}}
IMHO:

- we cite twice that we need to copy the `p` dir to each alpha server, thus we should remove line 151 and replace it with this notice bar.
- Move the notice bar after the diagram

2021-02-15 13:51 UTC, OmarAyo requested changes
after addressing the two comments LGTM

2021-02-16 15:34 UTC, bucanero commented on content/deploy/fast-data-loading/bulk-loader.md
> +![Bulk Loader diagram](/images/deploy/bulk-loader.png)
moved the diagram.
I'll check with the marketing team, but I still think that we can merge this PR with the current diagram, and update the image when available.

2021-02-16 15:43 UTC, bucanero commented on content/deploy/fast-data-loading/bulk-loader.md
> +{{% /notice %}}
I'm keeping both mentions to reinforce the message that each server needs a copy of the `p` folder

2021-02-17 06:55 UTC, aaroncarey approved these changes

2021-02-17 12:08 UTC, merged