update docs for python client
dgraph-io/dgraph-docs pull request #575
Opened 2023-05-17 03:20 UTC by mangalaman93

2023-05-17 10:18 UTC, rarvikar requested changes
Thanks for updating the docs !

Under the table for "Supported versions", shouldn't the pydgraph version be 21.3.x rather than 21.3.0 ? For example, a Dgraph v21.03.2 backend can work with multiple pydgraph versions v21.3.0, v21.3.1 and v21.3.2. So the table seems to indicate that v21 backends only work with a specific version of pydgraph - v21.3.0, which is misleading.  
Also, can we change Dgraph version in the table, from `21.X.Y` to `21.03.X` and `22.X.Y` to `22.0.X` ?

2023-05-19 16:02 UTC, rderbier approved these changes

2023-05-19 16:02 UTC, rderbier commented on content/dql/clients/python.md
> +them as follows:
```suggestion
Create the 'client_stub' using the gRPC endpoint and the API key:
```

2023-05-23 05:59 UTC, mangalaman93 commented
> For example, a Dgraph v21.03.2 backend can work with multiple pydgraph versions v21.3.0, v21.3.1 and v21.3.2.

We don't test for it, not sure whether we should say something like this in the README. Maybe it is easy enough to add tests against different Dgraph versions and build this table. Do you think that'd be useful?

2023-08-03 09:45 UTC, Rajakavitha1 commented
Hi @mangalaman93 !!! As a part of the docs revamp efforts we have removed this content from Docs and linked it to the repo to avoid duplication of update and maintenance efforts. https://github.com/dgraph-io/dgraph-docs/pull/610

2023-08-03 10:37 UTC, closed without merging