Update predicate-indexing.md
dgraph-io/dgraph-docs pull request #584
Opened 2023-05-22 12:25 UTC by damonfeldman

Updated with details of how a term token is defined, and added a link to the custom tokenizer page.

2023-05-22 12:29 UTC, rarvikar approved these changes
LGTM

2023-05-22 19:54 UTC, MichelDiz approved these changes

2023-06-03 00:46 UTC, MichelDiz requested changes

2023-06-03 00:46 UTC, MichelDiz commented on content/dql/predicate-indexing.md
> +If required, [custom tokenizers](/query-language/indexing-custom-tokenizers/) (which turn a value into one or more indexable values) can be implmented.
implmented -> implemented

2024-07-18 14:11 UTC, closed without merging