Update _index.md
dgraph-io/dgraph-docs pull request #618
Opened 2023-07-13 17:44 UTC by aaqibb13

Topic: Docs(GraphQL): Fix typo in offset
Description:
1. Fix typo in offset in /graphql endpoint
```diff
- offest
+ offset
```
The link to the page is: https://dgraph.io/docs/graphql/graphql-clients/endpoint/

2023-07-13 17:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=618) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph-docs?pullRequest=618) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph-docs?pullRequest=618) it.</sub>

2023-07-17 03:50 UTC, MichelDiz approved these changes

2023-07-17 03:50 UTC, MichelDiz requested changes
Need CLA

2024-07-14 12:31 UTC, aaqibb13 commented
The CLA was signed.

2024-07-16 13:24 UTC, ryanfoxtyler approved these changes

2024-07-16 13:24 UTC, merged