docs (enterprise): Create documentation for multi-tenancy
dgraph-io/dgraph-docs pull request #71
Opened 2021-02-23 14:48 UTC by bucanero

Fixes DOC-138

2021-02-23 15:34 UTC, NamanJain8 requested changes

2021-02-23 15:34 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +
Namespace can be created using `/admin` endpoint. 
Sample looks like:
```graphql
mutation {
 addNamespace
  {
    namespaceId
    message
  }
}
```
Similarly, the deletion looks like:
```graphql
mutation {
     deleteNamespace(input: {namespaceId: 1})
    {
    namespaceId
    message
  }
}
```
Also, we need to pass the JWT access token in `X-Dgraph-AccessToken` header.

2021-02-23 15:34 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +Backups are currently cluster-wide only, but [exports](#exports) can be created by namespace.
Only guardian of galaxy can trigger backup. Exports can be created by guardian of the namespace.

2021-02-23 15:34 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +The export function creates a new folder for each namespace, and each folder contains the exported `.rdf` and schema file.
Guardian of the galaxy can export for the whole cluster, in which case a single folder contains the export of all the namespaces in a single rdf file, single schema file.

While guardians of a namespace can trigger the export for their namespace.

2021-02-23 15:34 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +  export(input: {format: "json", namespace:"foo"}) {
namespaces are uint64

2021-02-23 15:34 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +}
For guardian of galaxy, if you don't pass a namespace it will export data for all namespaces. Else, if you want to export a specific namespace, pass it in parameter.

Example:
To export all namespaces: (Note that this is valid only for guardian of galaxy)
```graphql
mutation {
  export(input: {format: "rdf"}) {
    response {
      message
    }
  }
}
```
To export a specific namespace, say 2:
```graphql
mutation {
  export(input: {format: "rdf", namespace:2}) {
    response {
      message
    }
  }
}
```

2021-02-24 12:29 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +}
fixed

2021-02-24 12:29 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +  export(input: {format: "json", namespace:"foo"}) {
fixed

2021-02-24 12:29 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +Backups are currently cluster-wide only, but [exports](#exports) can be created by namespace.
fixed

2021-02-24 12:30 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +The export function creates a new folder for each namespace, and each folder contains the exported `.rdf` and schema file.
fixed

2021-02-24 12:52 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +
fixed

2021-02-24 13:15 UTC, NamanJain8 requested changes
A bunch of comments. Rest looks good.

2021-02-24 13:15 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +  - They can export their namespace
Guardians of the Namespace can export their namespace, not the normal user.

2021-02-24 13:15 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +Only members of the [Guardians of the Galaxy](#guardians-of-the-galaxy) (`dgraph-guardians`) group can create a namespace.
Do we want to coin another term `dgraph-guardians`?

2021-02-24 13:15 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +A namespace can be dropped by calling `/admin` with the `deleteNamespace()` mutation.
remove () from deleteNamespace.

2021-02-24 13:15 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +The export function creates a new folder for each namespace, and each folder contains the exported `.rdf` and schema file.
I think the above line can be updated. 
Add:
Guardian of a namespace can create an export for their namespace.

Also, maybe add as a note that RDFs/schema contain the namespace information.

2021-02-24 13:15 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +0x01 "name" "ibrahim" .          -> this goes to namespace 0x00
```suggestion
```rdf
<0x01> "name" "ibrahim" <0x12> .     -> this belongs to namespace 0x12
<0x01> "name" "ibrahim" <0x0> .       -> this belongs to namespace 0x00
```

2021-02-24 13:20 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +A namespace can be dropped by calling `/admin` with the `deleteNamespace()` mutation.
fixed

2021-02-24 13:21 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +Only members of the [Guardians of the Galaxy](#guardians-of-the-galaxy) (`dgraph-guardians`) group can create a namespace.
removed reference to `dgraph-guardians`

2021-02-24 13:22 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +  - They can export their namespace
fixed

2021-02-24 13:36 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +A user can be part of multiple namespaces, but the user has to be created separately for each namespace.
reworded for clarity

2021-02-24 13:56 UTC, NamanJain8 commented on content/enterprise-features/multitenancy.md
> +The export function creates a new folder for each namespace, and each folder contains the exported `.rdf` and schema file.
@bucanero I think this is unresolved.

2021-02-24 13:59 UTC, NamanJain8 approved these changes
Please resolve the comment I have.
Looks good technically. Maybe add some TODOs as comments to update the docs when the other sections of doc (like other graphql mutations/ changing password) are added.

2021-02-24 14:11 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +The export function creates a new folder for each namespace, and each folder contains the exported `.rdf` and schema file.
@NamanJain8, the reference about `Guardian of a namespace can create an export for their namespace` is there inside a `Note` box, see line 136:

```
{{% notice "note" %}}
Guardians of a Namespace can trigger an Export for their namespace.
{{% /notice %}}
```

I can add it to the paragraph, but it seems it would be too redundant.

2021-02-24 14:19 UTC, bucanero commented on content/enterprise-features/multitenancy.md
> +The export function creates a new folder for each namespace, and each folder contains the exported `.rdf` and schema file.
I've also added a line about the rdf/schema containing namespace information.

2021-02-24 15:24 UTC, merged