Bucanero/dql subscribe
dgraph-io/dgraph-docs pull request #84
Opened 2021-03-02 22:31 UTC by bucanero

Fixes DOC-157

2021-03-03 16:48 UTC, JatinDevDG requested changes

2021-03-03 16:49 UTC, JatinDevDG approved these changes

2021-03-04 12:22 UTC, bucanero commented on content/graphql/subscriptions/index.md
> +This directive also supports DQL in custom queries.
fixed

2021-03-04 12:25 UTC, bucanero commented on content/graphql/subscriptions/index.md
> +
fixed

2021-03-04 12:34 UTC, bucanero commented on content/graphql/subscriptions/index.md
> +
fixed

2021-03-04 12:39 UTC, merged