Docs (GraphQL): 21.03 feature documentation for GraphQL Upserts
dgraph-io/dgraph-docs pull request #88
Opened 2021-03-05 10:14 UTC by selectiveduplicate

Documentation for GraphQL upserts as per PR: https://github.com/dgraph-io/dgraph/pull/7433.
Fixes [DOC-167](https://dgraph.atlassian.net/browse/DOC-167).

2021-03-07 12:57 UTC, bucanero commented on content/graphql/mutations/upsert.md
> +Upsert mutations allow you to perform `add` or `update` operations based on whether a particular ID exists in the database. The IDs must be external IDs, defined using the `@id` directive in the sche
```suggestion
Upsert mutations allow you to perform `add` or `update` operations based on whether a particular `ID` exists in the database. The IDs must be external IDs, defined using the `@id` directive in the schema.
```

2021-03-07 13:00 UTC, bucanero commented on content/graphql/mutations/upsert.md
> +We use the following schema to demonstrate how upserts work in GraphQL:
```suggestion
For example, to demonstrate how upserts work in GraphQL, take the following schema:
```

2021-03-07 13:00 UTC, bucanero commented on content/graphql/mutations/upsert.md
> +Dgraph automatically generates input and return types in the schema for the add mutation, as shown below:
```suggestion
Dgraph automatically generates input and return types in the schema for the `add` mutation, as shown below:
```

2021-03-07 13:00 UTC, bucanero commented on content/graphql/mutations/upsert.md
> +Suppose we want to update the `text` field of a post with the ID `mm2`. But we also want to create a new post with that ID in case it doesn't already exist. To do this, we use the `addPost` mutation,
```suggestion
Suppose you want to update the `text` field of a post with the ID `mm2`. But you also want to create a new post with that ID in case it doesn't already exist. To do this, you use the `addPost` mutation, but with an additional input variable `upsert`.  
```

2021-03-07 13:01 UTC, bucanero commented on content/graphql/mutations/upsert.md
> +This is a Boolean variable. Setting it to `true` will change the default behavior of an `add` operation to an upsert operation.
```suggestion
This is a `Boolean` variable. Setting it to `true` will change the default behavior of an `add` operation to an upsert operation.
```

2021-03-07 13:03 UTC, bucanero commented on content/graphql/mutations/upsert.md
> +* The default value of `uspert` will be false, for backward compatibility.
```suggestion
* The default value of `uspert` will be `false`, for backward compatibility.
```

2021-03-07 13:04 UTC, bucanero commented on content/graphql/mutations/upsert.md
> +* The current behavior of Add and Update mutations is such that they do not update deep level nodes. So Add mutations with `upsert` set to `true` will only update values at the root level.
```suggestion
* The current behavior of `Add` and `Update` mutations is such that they do not update deep level nodes. So Add mutations with `upsert` set to `true` will only update values at the root level. 
```

2021-03-07 13:06 UTC, bucanero approved these changes
hi @selectiveduplicate 

I've added some small comments related to styling, everything looks good.
Thanks for your help! 👍

2021-03-10 11:02 UTC, vmrajas commented on content/graphql/mutations/upsert.md
> +description = "Upsert mutations allow you to perform `add` or `update` operations based on whether a particular ID exists in the database"
Can we use XID instead of ID. I don't want Users to get confused with ID type.

2021-03-10 11:05 UTC, vmrajas commented on content/graphql/mutations/upsert.md
> +	datePublished: DateTime
Let's remove this field also.

2021-03-10 11:07 UTC, vmrajas commented on content/graphql/mutations/upsert.md
> +addPost(input: [AddPostInput!]!): AddPostPayload
This has changed to addPost(input : [AddPostInput!]! , upsret: Boolean) : AddPostPayload

2021-03-10 11:07 UTC, vmrajas commented on content/graphql/mutations/upsert.md
> +addPost(input: [AddPostInput!]!): AddPostPayload
This may also need to be updated in the Add docs.

2021-03-10 11:08 UTC, vmrajas commented on content/graphql/mutations/upsert.md
> +This is a `Boolean` variable. Setting it to `true` will change the default behavior of an `add` operation to an upsert operation.
'Default behaviour to an upsert operation'  --> This does not sound right. Can you remove this.

2021-03-10 11:09 UTC, vmrajas commented on content/graphql/mutations/upsert.md
> +
Good Job with writing these notes.

2021-03-10 11:15 UTC, vmrajas requested changes
I will also like to see a link from Add page to Upsert. Upsert is Add (with a slight modification) and Users may like to see it from Add page. 

Also somewhat unrelated, Can the name of Deep page be changed to Deep mutations or Deep Level Mutations. The name 'Deep' did not make much sense to me.

2021-03-10 17:09 UTC, vmrajas commented on content/graphql/mutations/add.md
> +addPost(input: [AddPostInput!]!, upsert: Boolean): AddPostPayload
No need to update this as Post does not contain an @id field. I thought earlier that Post is same in Add and Upsert pages.

2021-03-10 17:12 UTC, vmrajas commented on content/graphql/mutations/add.md
> +addPost(input: [AddPostInput!]!, upsert: Boolean): AddPostPayload
Or have an @id field in type Post.

2021-03-10 17:12 UTC, vmrajas approved these changes
LGTM

2021-03-10 18:18 UTC, merged